#pragma once
#include <string>
#include "../Tools/tools.h"

enum class Command {     
    none               , 
    c_mr_mr_mov        , c_mr_r_mov         , c_mr_t_mov         , c_r_mr_mov         , c_r_r_mov          , c_r_t_mov          , b_mr_mr_mov        , b_mr_r_mov         , b_mr_t_mov         , b_r_mr_mov         , 
    b_r_r_mov          , b_r_t_mov          , i16_mr_mr_mov      , i16_mr_r_mov       , i16_mr_t_mov       , i16_r_mr_mov       , i16_r_r_mov        , i16_r_t_mov        , u16_mr_mr_mov      , u16_mr_r_mov       , 
    u16_mr_t_mov       , u16_r_mr_mov       , u16_r_r_mov        , u16_r_t_mov        , i32_mr_mr_mov      , i32_mr_r_mov       , i32_mr_t_mov       , i32_r_mr_mov       , i32_r_r_mov        , i32_r_t_mov        , 
    u32_mr_mr_mov      , u32_mr_r_mov       , u32_mr_t_mov       , u32_r_mr_mov       , u32_r_r_mov        , u32_r_t_mov        , i64_mr_mr_mov      , i64_mr_r_mov       , i64_mr_t_mov       , i64_r_mr_mov       , 
    i64_r_r_mov        , i64_r_t_mov        , u64_mr_mr_mov      , u64_mr_r_mov       , u64_mr_t_mov       , u64_r_mr_mov       , u64_r_r_mov        , u64_r_t_mov        , f32_mr_mr_mov      , f32_mr_r_mov       , 
    f32_mr_t_mov       , f32_r_mr_mov       , f32_r_r_mov        , f32_r_t_mov        , f64_mr_mr_mov      , f64_mr_r_mov       , f64_mr_t_mov       , f64_r_mr_mov       , f64_r_r_mov        , f64_r_t_mov        , 
    o_mr_mr_mov        , o_mr_r_mov         , o_mr_t_mov         , o_r_mr_mov         , o_r_r_mov          , o_r_t_mov          , B_mr_mr_mov        , B_mr_r_mov         , B_mr_t_mov         , B_r_mr_mov         , 
    B_r_r_mov          , B_r_t_mov          , 
    c_r_mr_addmov      , c_r_mr_submov      , c_r_mr_mulmov      , c_r_mr_divmov      , c_r_r_addmov       , c_r_r_submov       , c_r_r_mulmov       , c_r_r_divmov       , c_r_t_addmov       , c_r_t_submov       , 
    c_r_t_mulmov       , c_r_t_divmov       , c_mr_mr_addmov     , c_mr_mr_submov     , c_mr_mr_mulmov     , c_mr_mr_divmov     , c_mr_r_addmov      , c_mr_r_submov      , c_mr_r_mulmov      , c_mr_r_divmov      , 
    c_mr_t_addmov      , c_mr_t_submov      , c_mr_t_mulmov      , c_mr_t_divmov      , b_r_mr_addmov      , b_r_mr_submov      , b_r_mr_mulmov      , b_r_mr_divmov      , b_r_r_addmov       , b_r_r_submov       , 
    b_r_r_mulmov       , b_r_r_divmov       , b_r_t_addmov       , b_r_t_submov       , b_r_t_mulmov       , b_r_t_divmov       , b_mr_mr_addmov     , b_mr_mr_submov     , b_mr_mr_mulmov     , b_mr_mr_divmov     , 
    b_mr_r_addmov      , b_mr_r_submov      , b_mr_r_mulmov      , b_mr_r_divmov      , b_mr_t_addmov      , b_mr_t_submov      , b_mr_t_mulmov      , b_mr_t_divmov      , i16_r_mr_addmov    , i16_r_mr_submov    , 
    i16_r_mr_mulmov    , i16_r_mr_divmov    , i16_r_r_addmov     , i16_r_r_submov     , i16_r_r_mulmov     , i16_r_r_divmov     , i16_r_t_addmov     , i16_r_t_submov     , i16_r_t_mulmov     , i16_r_t_divmov     , 
    i16_mr_mr_addmov   , i16_mr_mr_submov   , i16_mr_mr_mulmov   , i16_mr_mr_divmov   , i16_mr_r_addmov    , i16_mr_r_submov    , i16_mr_r_mulmov    , i16_mr_r_divmov    , i16_mr_t_addmov    , i16_mr_t_submov    , 
    i16_mr_t_mulmov    , i16_mr_t_divmov    , u16_r_mr_addmov    , u16_r_mr_submov    , u16_r_mr_mulmov    , u16_r_mr_divmov    , u16_r_r_addmov     , u16_r_r_submov     , u16_r_r_mulmov     , u16_r_r_divmov     , 
    u16_r_t_addmov     , u16_r_t_submov     , u16_r_t_mulmov     , u16_r_t_divmov     , u16_mr_mr_addmov   , u16_mr_mr_submov   , u16_mr_mr_mulmov   , u16_mr_mr_divmov   , u16_mr_r_addmov    , u16_mr_r_submov    , 
    u16_mr_r_mulmov    , u16_mr_r_divmov    , u16_mr_t_addmov    , u16_mr_t_submov    , u16_mr_t_mulmov    , u16_mr_t_divmov    , i32_r_mr_addmov    , i32_r_mr_submov    , i32_r_mr_mulmov    , i32_r_mr_divmov    , 
    i32_r_r_addmov     , i32_r_r_submov     , i32_r_r_mulmov     , i32_r_r_divmov     , i32_r_t_addmov     , i32_r_t_submov     , i32_r_t_mulmov     , i32_r_t_divmov     , i32_mr_mr_addmov   , i32_mr_mr_submov   , 
    i32_mr_mr_mulmov   , i32_mr_mr_divmov   , i32_mr_r_addmov    , i32_mr_r_submov    , i32_mr_r_mulmov    , i32_mr_r_divmov    , i32_mr_t_addmov    , i32_mr_t_submov    , i32_mr_t_mulmov    , i32_mr_t_divmov    , 
    u32_r_mr_addmov    , u32_r_mr_submov    , u32_r_mr_mulmov    , u32_r_mr_divmov    , u32_r_r_addmov     , u32_r_r_submov     , u32_r_r_mulmov     , u32_r_r_divmov     , u32_r_t_addmov     , u32_r_t_submov     , 
    u32_r_t_mulmov     , u32_r_t_divmov     , u32_mr_mr_addmov   , u32_mr_mr_submov   , u32_mr_mr_mulmov   , u32_mr_mr_divmov   , u32_mr_r_addmov    , u32_mr_r_submov    , u32_mr_r_mulmov    , u32_mr_r_divmov    , 
    u32_mr_t_addmov    , u32_mr_t_submov    , u32_mr_t_mulmov    , u32_mr_t_divmov    , i64_r_mr_addmov    , i64_r_mr_submov    , i64_r_mr_mulmov    , i64_r_mr_divmov    , i64_r_r_addmov     , i64_r_r_submov     , 
    i64_r_r_mulmov     , i64_r_r_divmov     , i64_r_t_addmov     , i64_r_t_submov     , i64_r_t_mulmov     , i64_r_t_divmov     , i64_mr_mr_addmov   , i64_mr_mr_submov   , i64_mr_mr_mulmov   , i64_mr_mr_divmov   , 
    i64_mr_r_addmov    , i64_mr_r_submov    , i64_mr_r_mulmov    , i64_mr_r_divmov    , i64_mr_t_addmov    , i64_mr_t_submov    , i64_mr_t_mulmov    , i64_mr_t_divmov    , u64_r_mr_addmov    , u64_r_mr_submov    , 
    u64_r_mr_mulmov    , u64_r_mr_divmov    , u64_r_r_addmov     , u64_r_r_submov     , u64_r_r_mulmov     , u64_r_r_divmov     , u64_r_t_addmov     , u64_r_t_submov     , u64_r_t_mulmov     , u64_r_t_divmov     , 
    u64_mr_mr_addmov   , u64_mr_mr_submov   , u64_mr_mr_mulmov   , u64_mr_mr_divmov   , u64_mr_r_addmov    , u64_mr_r_submov    , u64_mr_r_mulmov    , u64_mr_r_divmov    , u64_mr_t_addmov    , u64_mr_t_submov    , 
    u64_mr_t_mulmov    , u64_mr_t_divmov    , f32_r_mr_addmov    , f32_r_mr_submov    , f32_r_mr_mulmov    , f32_r_mr_divmov    , f32_r_r_addmov     , f32_r_r_submov     , f32_r_r_mulmov     , f32_r_r_divmov     , 
    f32_r_t_addmov     , f32_r_t_submov     , f32_r_t_mulmov     , f32_r_t_divmov     , f32_mr_mr_addmov   , f32_mr_mr_submov   , f32_mr_mr_mulmov   , f32_mr_mr_divmov   , f32_mr_r_addmov    , f32_mr_r_submov    , 
    f32_mr_r_mulmov    , f32_mr_r_divmov    , f32_mr_t_addmov    , f32_mr_t_submov    , f32_mr_t_mulmov    , f32_mr_t_divmov    , f64_r_mr_addmov    , f64_r_mr_submov    , f64_r_mr_mulmov    , f64_r_mr_divmov    , 
    f64_r_r_addmov     , f64_r_r_submov     , f64_r_r_mulmov     , f64_r_r_divmov     , f64_r_t_addmov     , f64_r_t_submov     , f64_r_t_mulmov     , f64_r_t_divmov     , f64_mr_mr_addmov   , f64_mr_mr_submov   , 
    f64_mr_mr_mulmov   , f64_mr_mr_divmov   , f64_mr_r_addmov    , f64_mr_r_submov    , f64_mr_r_mulmov    , f64_mr_r_divmov    , f64_mr_t_addmov    , f64_mr_t_submov    , f64_mr_t_mulmov    , f64_mr_t_divmov    , 
    B_r_mr_addmov      , B_r_mr_submov      , B_r_mr_mulmov      , B_r_mr_divmov      , B_r_r_addmov       , B_r_r_submov       , B_r_r_mulmov       , B_r_r_divmov       , B_r_t_addmov       , B_r_t_submov       , 
    B_r_t_mulmov       , B_r_t_divmov       , B_mr_mr_addmov     , B_mr_mr_submov     , B_mr_mr_mulmov     , B_mr_mr_divmov     , B_mr_r_addmov      , B_mr_r_submov      , B_mr_r_mulmov      , B_mr_r_divmov      , 
    B_mr_t_addmov      , B_mr_t_submov      , B_mr_t_mulmov      , B_mr_t_divmov      , 
    c_r_mr_andmov      , c_r_mr_ormov       , c_r_mr_xormov      , c_r_mr_shlmov      , c_r_mr_shrmov      , c_r_mr_modmov      , c_r_r_andmov       , c_r_r_ormov        , c_r_r_xormov       , c_r_r_shlmov       , 
    c_r_r_shrmov       , c_r_r_modmov       , c_r_t_andmov       , c_r_t_ormov        , c_r_t_xormov       , c_r_t_shlmov       , c_r_t_shrmov       , c_r_t_modmov       , c_mr_mr_andmov     , c_mr_mr_ormov      , 
    c_mr_mr_xormov     , c_mr_mr_shlmov     , c_mr_mr_shrmov     , c_mr_mr_modmov     , c_mr_r_andmov      , c_mr_r_ormov       , c_mr_r_xormov      , c_mr_r_shlmov      , c_mr_r_shrmov      , c_mr_r_modmov      , 
    c_mr_t_andmov      , c_mr_t_ormov       , c_mr_t_xormov      , c_mr_t_shlmov      , c_mr_t_shrmov      , c_mr_t_modmov      , b_r_mr_andmov      , b_r_mr_ormov       , b_r_mr_xormov      , b_r_mr_shlmov      , 
    b_r_mr_shrmov      , b_r_mr_modmov      , b_r_r_andmov       , b_r_r_ormov        , b_r_r_xormov       , b_r_r_shlmov       , b_r_r_shrmov       , b_r_r_modmov       , b_r_t_andmov       , b_r_t_ormov        , 
    b_r_t_xormov       , b_r_t_shlmov       , b_r_t_shrmov       , b_r_t_modmov       , b_mr_mr_andmov     , b_mr_mr_ormov      , b_mr_mr_xormov     , b_mr_mr_shlmov     , b_mr_mr_shrmov     , b_mr_mr_modmov     , 
    b_mr_r_andmov      , b_mr_r_ormov       , b_mr_r_xormov      , b_mr_r_shlmov      , b_mr_r_shrmov      , b_mr_r_modmov      , b_mr_t_andmov      , b_mr_t_ormov       , b_mr_t_xormov      , b_mr_t_shlmov      , 
    b_mr_t_shrmov      , b_mr_t_modmov      , i16_r_mr_andmov    , i16_r_mr_ormov     , i16_r_mr_xormov    , i16_r_mr_shlmov    , i16_r_mr_shrmov    , i16_r_mr_modmov    , i16_r_r_andmov     , i16_r_r_ormov      , 
    i16_r_r_xormov     , i16_r_r_shlmov     , i16_r_r_shrmov     , i16_r_r_modmov     , i16_r_t_andmov     , i16_r_t_ormov      , i16_r_t_xormov     , i16_r_t_shlmov     , i16_r_t_shrmov     , i16_r_t_modmov     , 
    i16_mr_mr_andmov   , i16_mr_mr_ormov    , i16_mr_mr_xormov   , i16_mr_mr_shlmov   , i16_mr_mr_shrmov   , i16_mr_mr_modmov   , i16_mr_r_andmov    , i16_mr_r_ormov     , i16_mr_r_xormov    , i16_mr_r_shlmov    , 
    i16_mr_r_shrmov    , i16_mr_r_modmov    , i16_mr_t_andmov    , i16_mr_t_ormov     , i16_mr_t_xormov    , i16_mr_t_shlmov    , i16_mr_t_shrmov    , i16_mr_t_modmov    , u16_r_mr_andmov    , u16_r_mr_ormov     , 
    u16_r_mr_xormov    , u16_r_mr_shlmov    , u16_r_mr_shrmov    , u16_r_mr_modmov    , u16_r_r_andmov     , u16_r_r_ormov      , u16_r_r_xormov     , u16_r_r_shlmov     , u16_r_r_shrmov     , u16_r_r_modmov     , 
    u16_r_t_andmov     , u16_r_t_ormov      , u16_r_t_xormov     , u16_r_t_shlmov     , u16_r_t_shrmov     , u16_r_t_modmov     , u16_mr_mr_andmov   , u16_mr_mr_ormov    , u16_mr_mr_xormov   , u16_mr_mr_shlmov   , 
    u16_mr_mr_shrmov   , u16_mr_mr_modmov   , u16_mr_r_andmov    , u16_mr_r_ormov     , u16_mr_r_xormov    , u16_mr_r_shlmov    , u16_mr_r_shrmov    , u16_mr_r_modmov    , u16_mr_t_andmov    , u16_mr_t_ormov     , 
    u16_mr_t_xormov    , u16_mr_t_shlmov    , u16_mr_t_shrmov    , u16_mr_t_modmov    , i32_r_mr_andmov    , i32_r_mr_ormov     , i32_r_mr_xormov    , i32_r_mr_shlmov    , i32_r_mr_shrmov    , i32_r_mr_modmov    , 
    i32_r_r_andmov     , i32_r_r_ormov      , i32_r_r_xormov     , i32_r_r_shlmov     , i32_r_r_shrmov     , i32_r_r_modmov     , i32_r_t_andmov     , i32_r_t_ormov      , i32_r_t_xormov     , i32_r_t_shlmov     , 
    i32_r_t_shrmov     , i32_r_t_modmov     , i32_mr_mr_andmov   , i32_mr_mr_ormov    , i32_mr_mr_xormov   , i32_mr_mr_shlmov   , i32_mr_mr_shrmov   , i32_mr_mr_modmov   , i32_mr_r_andmov    , i32_mr_r_ormov     , 
    i32_mr_r_xormov    , i32_mr_r_shlmov    , i32_mr_r_shrmov    , i32_mr_r_modmov    , i32_mr_t_andmov    , i32_mr_t_ormov     , i32_mr_t_xormov    , i32_mr_t_shlmov    , i32_mr_t_shrmov    , i32_mr_t_modmov    , 
    u32_r_mr_andmov    , u32_r_mr_ormov     , u32_r_mr_xormov    , u32_r_mr_shlmov    , u32_r_mr_shrmov    , u32_r_mr_modmov    , u32_r_r_andmov     , u32_r_r_ormov      , u32_r_r_xormov     , u32_r_r_shlmov     , 
    u32_r_r_shrmov     , u32_r_r_modmov     , u32_r_t_andmov     , u32_r_t_ormov      , u32_r_t_xormov     , u32_r_t_shlmov     , u32_r_t_shrmov     , u32_r_t_modmov     , u32_mr_mr_andmov   , u32_mr_mr_ormov    , 
    u32_mr_mr_xormov   , u32_mr_mr_shlmov   , u32_mr_mr_shrmov   , u32_mr_mr_modmov   , u32_mr_r_andmov    , u32_mr_r_ormov     , u32_mr_r_xormov    , u32_mr_r_shlmov    , u32_mr_r_shrmov    , u32_mr_r_modmov    , 
    u32_mr_t_andmov    , u32_mr_t_ormov     , u32_mr_t_xormov    , u32_mr_t_shlmov    , u32_mr_t_shrmov    , u32_mr_t_modmov    , i64_r_mr_andmov    , i64_r_mr_ormov     , i64_r_mr_xormov    , i64_r_mr_shlmov    , 
    i64_r_mr_shrmov    , i64_r_mr_modmov    , i64_r_r_andmov     , i64_r_r_ormov      , i64_r_r_xormov     , i64_r_r_shlmov     , i64_r_r_shrmov     , i64_r_r_modmov     , i64_r_t_andmov     , i64_r_t_ormov      , 
    i64_r_t_xormov     , i64_r_t_shlmov     , i64_r_t_shrmov     , i64_r_t_modmov     , i64_mr_mr_andmov   , i64_mr_mr_ormov    , i64_mr_mr_xormov   , i64_mr_mr_shlmov   , i64_mr_mr_shrmov   , i64_mr_mr_modmov   , 
    i64_mr_r_andmov    , i64_mr_r_ormov     , i64_mr_r_xormov    , i64_mr_r_shlmov    , i64_mr_r_shrmov    , i64_mr_r_modmov    , i64_mr_t_andmov    , i64_mr_t_ormov     , i64_mr_t_xormov    , i64_mr_t_shlmov    , 
    i64_mr_t_shrmov    , i64_mr_t_modmov    , u64_r_mr_andmov    , u64_r_mr_ormov     , u64_r_mr_xormov    , u64_r_mr_shlmov    , u64_r_mr_shrmov    , u64_r_mr_modmov    , u64_r_r_andmov     , u64_r_r_ormov      , 
    u64_r_r_xormov     , u64_r_r_shlmov     , u64_r_r_shrmov     , u64_r_r_modmov     , u64_r_t_andmov     , u64_r_t_ormov      , u64_r_t_xormov     , u64_r_t_shlmov     , u64_r_t_shrmov     , u64_r_t_modmov     , 
    u64_mr_mr_andmov   , u64_mr_mr_ormov    , u64_mr_mr_xormov   , u64_mr_mr_shlmov   , u64_mr_mr_shrmov   , u64_mr_mr_modmov   , u64_mr_r_andmov    , u64_mr_r_ormov     , u64_mr_r_xormov    , u64_mr_r_shlmov    , 
    u64_mr_r_shrmov    , u64_mr_r_modmov    , u64_mr_t_andmov    , u64_mr_t_ormov     , u64_mr_t_xormov    , u64_mr_t_shlmov    , u64_mr_t_shrmov    , u64_mr_t_modmov    , 
    c_mr_mr_add        , c_mr_mr_sub        , c_mr_mr_mul        , c_mr_mr_div        , c_mr_r_add         , c_mr_r_sub         , c_mr_r_mul         , c_mr_r_div         , c_mr_t_add         , c_mr_t_sub         , 
    c_mr_t_mul         , c_mr_t_div         , c_r_mr_add         , c_r_mr_sub         , c_r_mr_mul         , c_r_mr_div         , c_r_r_add          , c_r_r_sub          , c_r_r_mul          , c_r_r_div          , 
    c_r_t_add          , c_r_t_sub          , c_r_t_mul          , c_r_t_div          , c_t_mr_add         , c_t_mr_sub         , c_t_mr_mul         , c_t_mr_div         , c_t_r_add          , c_t_r_sub          , 
    c_t_r_mul          , c_t_r_div          , c_t_t_add          , c_t_t_sub          , c_t_t_mul          , c_t_t_div          , b_mr_mr_add        , b_mr_mr_sub        , b_mr_mr_mul        , b_mr_mr_div        , 
    b_mr_r_add         , b_mr_r_sub         , b_mr_r_mul         , b_mr_r_div         , b_mr_t_add         , b_mr_t_sub         , b_mr_t_mul         , b_mr_t_div         , b_r_mr_add         , b_r_mr_sub         , 
    b_r_mr_mul         , b_r_mr_div         , b_r_r_add          , b_r_r_sub          , b_r_r_mul          , b_r_r_div          , b_r_t_add          , b_r_t_sub          , b_r_t_mul          , b_r_t_div          , 
    b_t_mr_add         , b_t_mr_sub         , b_t_mr_mul         , b_t_mr_div         , b_t_r_add          , b_t_r_sub          , b_t_r_mul          , b_t_r_div          , b_t_t_add          , b_t_t_sub          , 
    b_t_t_mul          , b_t_t_div          , i16_mr_mr_add      , i16_mr_mr_sub      , i16_mr_mr_mul      , i16_mr_mr_div      , i16_mr_r_add       , i16_mr_r_sub       , i16_mr_r_mul       , i16_mr_r_div       , 
    i16_mr_t_add       , i16_mr_t_sub       , i16_mr_t_mul       , i16_mr_t_div       , i16_r_mr_add       , i16_r_mr_sub       , i16_r_mr_mul       , i16_r_mr_div       , i16_r_r_add        , i16_r_r_sub        , 
    i16_r_r_mul        , i16_r_r_div        , i16_r_t_add        , i16_r_t_sub        , i16_r_t_mul        , i16_r_t_div        , i16_t_mr_add       , i16_t_mr_sub       , i16_t_mr_mul       , i16_t_mr_div       , 
    i16_t_r_add        , i16_t_r_sub        , i16_t_r_mul        , i16_t_r_div        , i16_t_t_add        , i16_t_t_sub        , i16_t_t_mul        , i16_t_t_div        , u16_mr_mr_add      , u16_mr_mr_sub      , 
    u16_mr_mr_mul      , u16_mr_mr_div      , u16_mr_r_add       , u16_mr_r_sub       , u16_mr_r_mul       , u16_mr_r_div       , u16_mr_t_add       , u16_mr_t_sub       , u16_mr_t_mul       , u16_mr_t_div       , 
    u16_r_mr_add       , u16_r_mr_sub       , u16_r_mr_mul       , u16_r_mr_div       , u16_r_r_add        , u16_r_r_sub        , u16_r_r_mul        , u16_r_r_div        , u16_r_t_add        , u16_r_t_sub        , 
    u16_r_t_mul        , u16_r_t_div        , u16_t_mr_add       , u16_t_mr_sub       , u16_t_mr_mul       , u16_t_mr_div       , u16_t_r_add        , u16_t_r_sub        , u16_t_r_mul        , u16_t_r_div        , 
    u16_t_t_add        , u16_t_t_sub        , u16_t_t_mul        , u16_t_t_div        , i32_mr_mr_add      , i32_mr_mr_sub      , i32_mr_mr_mul      , i32_mr_mr_div      , i32_mr_r_add       , i32_mr_r_sub       , 
    i32_mr_r_mul       , i32_mr_r_div       , i32_mr_t_add       , i32_mr_t_sub       , i32_mr_t_mul       , i32_mr_t_div       , i32_r_mr_add       , i32_r_mr_sub       , i32_r_mr_mul       , i32_r_mr_div       , 
    i32_r_r_add        , i32_r_r_sub        , i32_r_r_mul        , i32_r_r_div        , i32_r_t_add        , i32_r_t_sub        , i32_r_t_mul        , i32_r_t_div        , i32_t_mr_add       , i32_t_mr_sub       , 
    i32_t_mr_mul       , i32_t_mr_div       , i32_t_r_add        , i32_t_r_sub        , i32_t_r_mul        , i32_t_r_div        , i32_t_t_add        , i32_t_t_sub        , i32_t_t_mul        , i32_t_t_div        , 
    u32_mr_mr_add      , u32_mr_mr_sub      , u32_mr_mr_mul      , u32_mr_mr_div      , u32_mr_r_add       , u32_mr_r_sub       , u32_mr_r_mul       , u32_mr_r_div       , u32_mr_t_add       , u32_mr_t_sub       , 
    u32_mr_t_mul       , u32_mr_t_div       , u32_r_mr_add       , u32_r_mr_sub       , u32_r_mr_mul       , u32_r_mr_div       , u32_r_r_add        , u32_r_r_sub        , u32_r_r_mul        , u32_r_r_div        , 
    u32_r_t_add        , u32_r_t_sub        , u32_r_t_mul        , u32_r_t_div        , u32_t_mr_add       , u32_t_mr_sub       , u32_t_mr_mul       , u32_t_mr_div       , u32_t_r_add        , u32_t_r_sub        , 
    u32_t_r_mul        , u32_t_r_div        , u32_t_t_add        , u32_t_t_sub        , u32_t_t_mul        , u32_t_t_div        , i64_mr_mr_add      , i64_mr_mr_sub      , i64_mr_mr_mul      , i64_mr_mr_div      , 
    i64_mr_r_add       , i64_mr_r_sub       , i64_mr_r_mul       , i64_mr_r_div       , i64_mr_t_add       , i64_mr_t_sub       , i64_mr_t_mul       , i64_mr_t_div       , i64_r_mr_add       , i64_r_mr_sub       , 
    i64_r_mr_mul       , i64_r_mr_div       , i64_r_r_add        , i64_r_r_sub        , i64_r_r_mul        , i64_r_r_div        , i64_r_t_add        , i64_r_t_sub        , i64_r_t_mul        , i64_r_t_div        , 
    i64_t_mr_add       , i64_t_mr_sub       , i64_t_mr_mul       , i64_t_mr_div       , i64_t_r_add        , i64_t_r_sub        , i64_t_r_mul        , i64_t_r_div        , i64_t_t_add        , i64_t_t_sub        , 
    i64_t_t_mul        , i64_t_t_div        , u64_mr_mr_add      , u64_mr_mr_sub      , u64_mr_mr_mul      , u64_mr_mr_div      , u64_mr_r_add       , u64_mr_r_sub       , u64_mr_r_mul       , u64_mr_r_div       , 
    u64_mr_t_add       , u64_mr_t_sub       , u64_mr_t_mul       , u64_mr_t_div       , u64_r_mr_add       , u64_r_mr_sub       , u64_r_mr_mul       , u64_r_mr_div       , u64_r_r_add        , u64_r_r_sub        , 
    u64_r_r_mul        , u64_r_r_div        , u64_r_t_add        , u64_r_t_sub        , u64_r_t_mul        , u64_r_t_div        , u64_t_mr_add       , u64_t_mr_sub       , u64_t_mr_mul       , u64_t_mr_div       , 
    u64_t_r_add        , u64_t_r_sub        , u64_t_r_mul        , u64_t_r_div        , u64_t_t_add        , u64_t_t_sub        , u64_t_t_mul        , u64_t_t_div        , f32_mr_mr_add      , f32_mr_mr_sub      , 
    f32_mr_mr_mul      , f32_mr_mr_div      , f32_mr_r_add       , f32_mr_r_sub       , f32_mr_r_mul       , f32_mr_r_div       , f32_mr_t_add       , f32_mr_t_sub       , f32_mr_t_mul       , f32_mr_t_div       , 
    f32_r_mr_add       , f32_r_mr_sub       , f32_r_mr_mul       , f32_r_mr_div       , f32_r_r_add        , f32_r_r_sub        , f32_r_r_mul        , f32_r_r_div        , f32_r_t_add        , f32_r_t_sub        , 
    f32_r_t_mul        , f32_r_t_div        , f32_t_mr_add       , f32_t_mr_sub       , f32_t_mr_mul       , f32_t_mr_div       , f32_t_r_add        , f32_t_r_sub        , f32_t_r_mul        , f32_t_r_div        , 
    f32_t_t_add        , f32_t_t_sub        , f32_t_t_mul        , f32_t_t_div        , f64_mr_mr_add      , f64_mr_mr_sub      , f64_mr_mr_mul      , f64_mr_mr_div      , f64_mr_r_add       , f64_mr_r_sub       , 
    f64_mr_r_mul       , f64_mr_r_div       , f64_mr_t_add       , f64_mr_t_sub       , f64_mr_t_mul       , f64_mr_t_div       , f64_r_mr_add       , f64_r_mr_sub       , f64_r_mr_mul       , f64_r_mr_div       , 
    f64_r_r_add        , f64_r_r_sub        , f64_r_r_mul        , f64_r_r_div        , f64_r_t_add        , f64_r_t_sub        , f64_r_t_mul        , f64_r_t_div        , f64_t_mr_add       , f64_t_mr_sub       , 
    f64_t_mr_mul       , f64_t_mr_div       , f64_t_r_add        , f64_t_r_sub        , f64_t_r_mul        , f64_t_r_div        , f64_t_t_add        , f64_t_t_sub        , f64_t_t_mul        , f64_t_t_div        , 
    B_mr_mr_add        , B_mr_mr_sub        , B_mr_mr_mul        , B_mr_mr_div        , B_mr_r_add         , B_mr_r_sub         , B_mr_r_mul         , B_mr_r_div         , B_mr_t_add         , B_mr_t_sub         , 
    B_mr_t_mul         , B_mr_t_div         , B_r_mr_add         , B_r_mr_sub         , B_r_mr_mul         , B_r_mr_div         , B_r_r_add          , B_r_r_sub          , B_r_r_mul          , B_r_r_div          , 
    B_r_t_add          , B_r_t_sub          , B_r_t_mul          , B_r_t_div          , B_t_mr_add         , B_t_mr_sub         , B_t_mr_mul         , B_t_mr_div         , B_t_r_add          , B_t_r_sub          , 
    B_t_r_mul          , B_t_r_div          , B_t_t_add          , B_t_t_sub          , B_t_t_mul          , B_t_t_div          , 
    c_mr_mr_and        , c_mr_mr_or         , c_mr_mr_xor        , c_mr_mr_shl        , c_mr_mr_shr        , c_mr_mr_mod        , c_mr_r_and         , c_mr_r_or          , c_mr_r_xor         , c_mr_r_shl         , 
    c_mr_r_shr         , c_mr_r_mod         , c_mr_t_and         , c_mr_t_or          , c_mr_t_xor         , c_mr_t_shl         , c_mr_t_shr         , c_mr_t_mod         , c_r_mr_and         , c_r_mr_or          , 
    c_r_mr_xor         , c_r_mr_shl         , c_r_mr_shr         , c_r_mr_mod         , c_r_r_and          , c_r_r_or           , c_r_r_xor          , c_r_r_shl          , c_r_r_shr          , c_r_r_mod          , 
    c_r_t_and          , c_r_t_or           , c_r_t_xor          , c_r_t_shl          , c_r_t_shr          , c_r_t_mod          , c_t_mr_and         , c_t_mr_or          , c_t_mr_xor         , c_t_mr_shl         , 
    c_t_mr_shr         , c_t_mr_mod         , c_t_r_and          , c_t_r_or           , c_t_r_xor          , c_t_r_shl          , c_t_r_shr          , c_t_r_mod          , c_t_t_and          , c_t_t_or           , 
    c_t_t_xor          , c_t_t_shl          , c_t_t_shr          , c_t_t_mod          , b_mr_mr_and        , b_mr_mr_or         , b_mr_mr_xor        , b_mr_mr_shl        , b_mr_mr_shr        , b_mr_mr_mod        , 
    b_mr_r_and         , b_mr_r_or          , b_mr_r_xor         , b_mr_r_shl         , b_mr_r_shr         , b_mr_r_mod         , b_mr_t_and         , b_mr_t_or          , b_mr_t_xor         , b_mr_t_shl         , 
    b_mr_t_shr         , b_mr_t_mod         , b_r_mr_and         , b_r_mr_or          , b_r_mr_xor         , b_r_mr_shl         , b_r_mr_shr         , b_r_mr_mod         , b_r_r_and          , b_r_r_or           , 
    b_r_r_xor          , b_r_r_shl          , b_r_r_shr          , b_r_r_mod          , b_r_t_and          , b_r_t_or           , b_r_t_xor          , b_r_t_shl          , b_r_t_shr          , b_r_t_mod          , 
    b_t_mr_and         , b_t_mr_or          , b_t_mr_xor         , b_t_mr_shl         , b_t_mr_shr         , b_t_mr_mod         , b_t_r_and          , b_t_r_or           , b_t_r_xor          , b_t_r_shl          , 
    b_t_r_shr          , b_t_r_mod          , b_t_t_and          , b_t_t_or           , b_t_t_xor          , b_t_t_shl          , b_t_t_shr          , b_t_t_mod          , i16_mr_mr_and      , i16_mr_mr_or       , 
    i16_mr_mr_xor      , i16_mr_mr_shl      , i16_mr_mr_shr      , i16_mr_mr_mod      , i16_mr_r_and       , i16_mr_r_or        , i16_mr_r_xor       , i16_mr_r_shl       , i16_mr_r_shr       , i16_mr_r_mod       , 
    i16_mr_t_and       , i16_mr_t_or        , i16_mr_t_xor       , i16_mr_t_shl       , i16_mr_t_shr       , i16_mr_t_mod       , i16_r_mr_and       , i16_r_mr_or        , i16_r_mr_xor       , i16_r_mr_shl       , 
    i16_r_mr_shr       , i16_r_mr_mod       , i16_r_r_and        , i16_r_r_or         , i16_r_r_xor        , i16_r_r_shl        , i16_r_r_shr        , i16_r_r_mod        , i16_r_t_and        , i16_r_t_or         , 
    i16_r_t_xor        , i16_r_t_shl        , i16_r_t_shr        , i16_r_t_mod        , i16_t_mr_and       , i16_t_mr_or        , i16_t_mr_xor       , i16_t_mr_shl       , i16_t_mr_shr       , i16_t_mr_mod       , 
    i16_t_r_and        , i16_t_r_or         , i16_t_r_xor        , i16_t_r_shl        , i16_t_r_shr        , i16_t_r_mod        , i16_t_t_and        , i16_t_t_or         , i16_t_t_xor        , i16_t_t_shl        , 
    i16_t_t_shr        , i16_t_t_mod        , u16_mr_mr_and      , u16_mr_mr_or       , u16_mr_mr_xor      , u16_mr_mr_shl      , u16_mr_mr_shr      , u16_mr_mr_mod      , u16_mr_r_and       , u16_mr_r_or        , 
    u16_mr_r_xor       , u16_mr_r_shl       , u16_mr_r_shr       , u16_mr_r_mod       , u16_mr_t_and       , u16_mr_t_or        , u16_mr_t_xor       , u16_mr_t_shl       , u16_mr_t_shr       , u16_mr_t_mod       , 
    u16_r_mr_and       , u16_r_mr_or        , u16_r_mr_xor       , u16_r_mr_shl       , u16_r_mr_shr       , u16_r_mr_mod       , u16_r_r_and        , u16_r_r_or         , u16_r_r_xor        , u16_r_r_shl        , 
    u16_r_r_shr        , u16_r_r_mod        , u16_r_t_and        , u16_r_t_or         , u16_r_t_xor        , u16_r_t_shl        , u16_r_t_shr        , u16_r_t_mod        , u16_t_mr_and       , u16_t_mr_or        , 
    u16_t_mr_xor       , u16_t_mr_shl       , u16_t_mr_shr       , u16_t_mr_mod       , u16_t_r_and        , u16_t_r_or         , u16_t_r_xor        , u16_t_r_shl        , u16_t_r_shr        , u16_t_r_mod        , 
    u16_t_t_and        , u16_t_t_or         , u16_t_t_xor        , u16_t_t_shl        , u16_t_t_shr        , u16_t_t_mod        , i32_mr_mr_and      , i32_mr_mr_or       , i32_mr_mr_xor      , i32_mr_mr_shl      , 
    i32_mr_mr_shr      , i32_mr_mr_mod      , i32_mr_r_and       , i32_mr_r_or        , i32_mr_r_xor       , i32_mr_r_shl       , i32_mr_r_shr       , i32_mr_r_mod       , i32_mr_t_and       , i32_mr_t_or        , 
    i32_mr_t_xor       , i32_mr_t_shl       , i32_mr_t_shr       , i32_mr_t_mod       , i32_r_mr_and       , i32_r_mr_or        , i32_r_mr_xor       , i32_r_mr_shl       , i32_r_mr_shr       , i32_r_mr_mod       , 
    i32_r_r_and        , i32_r_r_or         , i32_r_r_xor        , i32_r_r_shl        , i32_r_r_shr        , i32_r_r_mod        , i32_r_t_and        , i32_r_t_or         , i32_r_t_xor        , i32_r_t_shl        , 
    i32_r_t_shr        , i32_r_t_mod        , i32_t_mr_and       , i32_t_mr_or        , i32_t_mr_xor       , i32_t_mr_shl       , i32_t_mr_shr       , i32_t_mr_mod       , i32_t_r_and        , i32_t_r_or         , 
    i32_t_r_xor        , i32_t_r_shl        , i32_t_r_shr        , i32_t_r_mod        , i32_t_t_and        , i32_t_t_or         , i32_t_t_xor        , i32_t_t_shl        , i32_t_t_shr        , i32_t_t_mod        , 
    u32_mr_mr_and      , u32_mr_mr_or       , u32_mr_mr_xor      , u32_mr_mr_shl      , u32_mr_mr_shr      , u32_mr_mr_mod      , u32_mr_r_and       , u32_mr_r_or        , u32_mr_r_xor       , u32_mr_r_shl       , 
    u32_mr_r_shr       , u32_mr_r_mod       , u32_mr_t_and       , u32_mr_t_or        , u32_mr_t_xor       , u32_mr_t_shl       , u32_mr_t_shr       , u32_mr_t_mod       , u32_r_mr_and       , u32_r_mr_or        , 
    u32_r_mr_xor       , u32_r_mr_shl       , u32_r_mr_shr       , u32_r_mr_mod       , u32_r_r_and        , u32_r_r_or         , u32_r_r_xor        , u32_r_r_shl        , u32_r_r_shr        , u32_r_r_mod        , 
    u32_r_t_and        , u32_r_t_or         , u32_r_t_xor        , u32_r_t_shl        , u32_r_t_shr        , u32_r_t_mod        , u32_t_mr_and       , u32_t_mr_or        , u32_t_mr_xor       , u32_t_mr_shl       , 
    u32_t_mr_shr       , u32_t_mr_mod       , u32_t_r_and        , u32_t_r_or         , u32_t_r_xor        , u32_t_r_shl        , u32_t_r_shr        , u32_t_r_mod        , u32_t_t_and        , u32_t_t_or         , 
    u32_t_t_xor        , u32_t_t_shl        , u32_t_t_shr        , u32_t_t_mod        , i64_mr_mr_and      , i64_mr_mr_or       , i64_mr_mr_xor      , i64_mr_mr_shl      , i64_mr_mr_shr      , i64_mr_mr_mod      , 
    i64_mr_r_and       , i64_mr_r_or        , i64_mr_r_xor       , i64_mr_r_shl       , i64_mr_r_shr       , i64_mr_r_mod       , i64_mr_t_and       , i64_mr_t_or        , i64_mr_t_xor       , i64_mr_t_shl       , 
    i64_mr_t_shr       , i64_mr_t_mod       , i64_r_mr_and       , i64_r_mr_or        , i64_r_mr_xor       , i64_r_mr_shl       , i64_r_mr_shr       , i64_r_mr_mod       , i64_r_r_and        , i64_r_r_or         , 
    i64_r_r_xor        , i64_r_r_shl        , i64_r_r_shr        , i64_r_r_mod        , i64_r_t_and        , i64_r_t_or         , i64_r_t_xor        , i64_r_t_shl        , i64_r_t_shr        , i64_r_t_mod        , 
    i64_t_mr_and       , i64_t_mr_or        , i64_t_mr_xor       , i64_t_mr_shl       , i64_t_mr_shr       , i64_t_mr_mod       , i64_t_r_and        , i64_t_r_or         , i64_t_r_xor        , i64_t_r_shl        , 
    i64_t_r_shr        , i64_t_r_mod        , i64_t_t_and        , i64_t_t_or         , i64_t_t_xor        , i64_t_t_shl        , i64_t_t_shr        , i64_t_t_mod        , u64_mr_mr_and      , u64_mr_mr_or       , 
    u64_mr_mr_xor      , u64_mr_mr_shl      , u64_mr_mr_shr      , u64_mr_mr_mod      , u64_mr_r_and       , u64_mr_r_or        , u64_mr_r_xor       , u64_mr_r_shl       , u64_mr_r_shr       , u64_mr_r_mod       , 
    u64_mr_t_and       , u64_mr_t_or        , u64_mr_t_xor       , u64_mr_t_shl       , u64_mr_t_shr       , u64_mr_t_mod       , u64_r_mr_and       , u64_r_mr_or        , u64_r_mr_xor       , u64_r_mr_shl       , 
    u64_r_mr_shr       , u64_r_mr_mod       , u64_r_r_and        , u64_r_r_or         , u64_r_r_xor        , u64_r_r_shl        , u64_r_r_shr        , u64_r_r_mod        , u64_r_t_and        , u64_r_t_or         , 
    u64_r_t_xor        , u64_r_t_shl        , u64_r_t_shr        , u64_r_t_mod        , u64_t_mr_and       , u64_t_mr_or        , u64_t_mr_xor       , u64_t_mr_shl       , u64_t_mr_shr       , u64_t_mr_mod       , 
    u64_t_r_and        , u64_t_r_or         , u64_t_r_xor        , u64_t_r_shl        , u64_t_r_shr        , u64_t_r_mod        , u64_t_t_and        , u64_t_t_or         , u64_t_t_xor        , u64_t_t_shl        , 
    u64_t_t_shr        , u64_t_t_mod        , 
    c_mr_not           , c_r_not            , c_t_not            , b_mr_not           , b_r_not            , b_t_not            , i16_mr_not         , i16_r_not          , i16_t_not          , u16_mr_not         , 
    u16_r_not          , u16_t_not          , i32_mr_not         , i32_r_not          , i32_t_not          , u32_mr_not         , u32_r_not          , u32_t_not          , i64_mr_not         , i64_r_not          , 
    i64_t_not          , u64_mr_not         , u64_r_not          , u64_t_not          , 
    c_mr_pinc          , c_mr_sinc          , c_mr_pdec          , c_mr_sdec          , c_r_pinc           , c_r_sinc           , c_r_pdec           , c_r_sdec           , b_mr_pinc          , b_mr_sinc          , 
    b_mr_pdec          , b_mr_sdec          , b_r_pinc           , b_r_sinc           , b_r_pdec           , b_r_sdec           , i16_mr_pinc        , i16_mr_sinc        , i16_mr_pdec        , i16_mr_sdec        , 
    i16_r_pinc         , i16_r_sinc         , i16_r_pdec         , i16_r_sdec         , u16_mr_pinc        , u16_mr_sinc        , u16_mr_pdec        , u16_mr_sdec        , u16_r_pinc         , u16_r_sinc         , 
    u16_r_pdec         , u16_r_sdec         , i32_mr_pinc        , i32_mr_sinc        , i32_mr_pdec        , i32_mr_sdec        , i32_r_pinc         , i32_r_sinc         , i32_r_pdec         , i32_r_sdec         , 
    u32_mr_pinc        , u32_mr_sinc        , u32_mr_pdec        , u32_mr_sdec        , u32_r_pinc         , u32_r_sinc         , u32_r_pdec         , u32_r_sdec         , i64_mr_pinc        , i64_mr_sinc        , 
    i64_mr_pdec        , i64_mr_sdec        , i64_r_pinc         , i64_r_sinc         , i64_r_pdec         , i64_r_sdec         , u64_mr_pinc        , u64_mr_sinc        , u64_mr_pdec        , u64_mr_sdec        , 
    u64_r_pinc         , u64_r_sinc         , u64_r_pdec         , u64_r_sdec         , 
    c_mr_mr_eq         , c_mr_mr_ne         , c_mr_mr_gt         , c_mr_mr_ge         , c_mr_mr_ls         , c_mr_mr_le         , c_mr_r_eq          , c_mr_r_ne          , c_mr_r_gt          , c_mr_r_ge          , 
    c_mr_r_ls          , c_mr_r_le          , c_mr_t_eq          , c_mr_t_ne          , c_mr_t_gt          , c_mr_t_ge          , c_mr_t_ls          , c_mr_t_le          , c_r_mr_eq          , c_r_mr_ne          , 
    c_r_mr_gt          , c_r_mr_ge          , c_r_mr_ls          , c_r_mr_le          , c_r_r_eq           , c_r_r_ne           , c_r_r_gt           , c_r_r_ge           , c_r_r_ls           , c_r_r_le           , 
    c_r_t_eq           , c_r_t_ne           , c_r_t_gt           , c_r_t_ge           , c_r_t_ls           , c_r_t_le           , c_t_mr_eq          , c_t_mr_ne          , c_t_mr_gt          , c_t_mr_ge          , 
    c_t_mr_ls          , c_t_mr_le          , c_t_r_eq           , c_t_r_ne           , c_t_r_gt           , c_t_r_ge           , c_t_r_ls           , c_t_r_le           , c_t_t_eq           , c_t_t_ne           , 
    c_t_t_gt           , c_t_t_ge           , c_t_t_ls           , c_t_t_le           , b_mr_mr_eq         , b_mr_mr_ne         , b_mr_mr_gt         , b_mr_mr_ge         , b_mr_mr_ls         , b_mr_mr_le         , 
    b_mr_r_eq          , b_mr_r_ne          , b_mr_r_gt          , b_mr_r_ge          , b_mr_r_ls          , b_mr_r_le          , b_mr_t_eq          , b_mr_t_ne          , b_mr_t_gt          , b_mr_t_ge          , 
    b_mr_t_ls          , b_mr_t_le          , b_r_mr_eq          , b_r_mr_ne          , b_r_mr_gt          , b_r_mr_ge          , b_r_mr_ls          , b_r_mr_le          , b_r_r_eq           , b_r_r_ne           , 
    b_r_r_gt           , b_r_r_ge           , b_r_r_ls           , b_r_r_le           , b_r_t_eq           , b_r_t_ne           , b_r_t_gt           , b_r_t_ge           , b_r_t_ls           , b_r_t_le           , 
    b_t_mr_eq          , b_t_mr_ne          , b_t_mr_gt          , b_t_mr_ge          , b_t_mr_ls          , b_t_mr_le          , b_t_r_eq           , b_t_r_ne           , b_t_r_gt           , b_t_r_ge           , 
    b_t_r_ls           , b_t_r_le           , b_t_t_eq           , b_t_t_ne           , b_t_t_gt           , b_t_t_ge           , b_t_t_ls           , b_t_t_le           , i16_mr_mr_eq       , i16_mr_mr_ne       , 
    i16_mr_mr_gt       , i16_mr_mr_ge       , i16_mr_mr_ls       , i16_mr_mr_le       , i16_mr_r_eq        , i16_mr_r_ne        , i16_mr_r_gt        , i16_mr_r_ge        , i16_mr_r_ls        , i16_mr_r_le        , 
    i16_mr_t_eq        , i16_mr_t_ne        , i16_mr_t_gt        , i16_mr_t_ge        , i16_mr_t_ls        , i16_mr_t_le        , i16_r_mr_eq        , i16_r_mr_ne        , i16_r_mr_gt        , i16_r_mr_ge        , 
    i16_r_mr_ls        , i16_r_mr_le        , i16_r_r_eq         , i16_r_r_ne         , i16_r_r_gt         , i16_r_r_ge         , i16_r_r_ls         , i16_r_r_le         , i16_r_t_eq         , i16_r_t_ne         , 
    i16_r_t_gt         , i16_r_t_ge         , i16_r_t_ls         , i16_r_t_le         , i16_t_mr_eq        , i16_t_mr_ne        , i16_t_mr_gt        , i16_t_mr_ge        , i16_t_mr_ls        , i16_t_mr_le        , 
    i16_t_r_eq         , i16_t_r_ne         , i16_t_r_gt         , i16_t_r_ge         , i16_t_r_ls         , i16_t_r_le         , i16_t_t_eq         , i16_t_t_ne         , i16_t_t_gt         , i16_t_t_ge         , 
    i16_t_t_ls         , i16_t_t_le         , u16_mr_mr_eq       , u16_mr_mr_ne       , u16_mr_mr_gt       , u16_mr_mr_ge       , u16_mr_mr_ls       , u16_mr_mr_le       , u16_mr_r_eq        , u16_mr_r_ne        , 
    u16_mr_r_gt        , u16_mr_r_ge        , u16_mr_r_ls        , u16_mr_r_le        , u16_mr_t_eq        , u16_mr_t_ne        , u16_mr_t_gt        , u16_mr_t_ge        , u16_mr_t_ls        , u16_mr_t_le        , 
    u16_r_mr_eq        , u16_r_mr_ne        , u16_r_mr_gt        , u16_r_mr_ge        , u16_r_mr_ls        , u16_r_mr_le        , u16_r_r_eq         , u16_r_r_ne         , u16_r_r_gt         , u16_r_r_ge         , 
    u16_r_r_ls         , u16_r_r_le         , u16_r_t_eq         , u16_r_t_ne         , u16_r_t_gt         , u16_r_t_ge         , u16_r_t_ls         , u16_r_t_le         , u16_t_mr_eq        , u16_t_mr_ne        , 
    u16_t_mr_gt        , u16_t_mr_ge        , u16_t_mr_ls        , u16_t_mr_le        , u16_t_r_eq         , u16_t_r_ne         , u16_t_r_gt         , u16_t_r_ge         , u16_t_r_ls         , u16_t_r_le         , 
    u16_t_t_eq         , u16_t_t_ne         , u16_t_t_gt         , u16_t_t_ge         , u16_t_t_ls         , u16_t_t_le         , i32_mr_mr_eq       , i32_mr_mr_ne       , i32_mr_mr_gt       , i32_mr_mr_ge       , 
    i32_mr_mr_ls       , i32_mr_mr_le       , i32_mr_r_eq        , i32_mr_r_ne        , i32_mr_r_gt        , i32_mr_r_ge        , i32_mr_r_ls        , i32_mr_r_le        , i32_mr_t_eq        , i32_mr_t_ne        , 
    i32_mr_t_gt        , i32_mr_t_ge        , i32_mr_t_ls        , i32_mr_t_le        , i32_r_mr_eq        , i32_r_mr_ne        , i32_r_mr_gt        , i32_r_mr_ge        , i32_r_mr_ls        , i32_r_mr_le        , 
    i32_r_r_eq         , i32_r_r_ne         , i32_r_r_gt         , i32_r_r_ge         , i32_r_r_ls         , i32_r_r_le         , i32_r_t_eq         , i32_r_t_ne         , i32_r_t_gt         , i32_r_t_ge         , 
    i32_r_t_ls         , i32_r_t_le         , i32_t_mr_eq        , i32_t_mr_ne        , i32_t_mr_gt        , i32_t_mr_ge        , i32_t_mr_ls        , i32_t_mr_le        , i32_t_r_eq         , i32_t_r_ne         , 
    i32_t_r_gt         , i32_t_r_ge         , i32_t_r_ls         , i32_t_r_le         , i32_t_t_eq         , i32_t_t_ne         , i32_t_t_gt         , i32_t_t_ge         , i32_t_t_ls         , i32_t_t_le         , 
    u32_mr_mr_eq       , u32_mr_mr_ne       , u32_mr_mr_gt       , u32_mr_mr_ge       , u32_mr_mr_ls       , u32_mr_mr_le       , u32_mr_r_eq        , u32_mr_r_ne        , u32_mr_r_gt        , u32_mr_r_ge        , 
    u32_mr_r_ls        , u32_mr_r_le        , u32_mr_t_eq        , u32_mr_t_ne        , u32_mr_t_gt        , u32_mr_t_ge        , u32_mr_t_ls        , u32_mr_t_le        , u32_r_mr_eq        , u32_r_mr_ne        , 
    u32_r_mr_gt        , u32_r_mr_ge        , u32_r_mr_ls        , u32_r_mr_le        , u32_r_r_eq         , u32_r_r_ne         , u32_r_r_gt         , u32_r_r_ge         , u32_r_r_ls         , u32_r_r_le         , 
    u32_r_t_eq         , u32_r_t_ne         , u32_r_t_gt         , u32_r_t_ge         , u32_r_t_ls         , u32_r_t_le         , u32_t_mr_eq        , u32_t_mr_ne        , u32_t_mr_gt        , u32_t_mr_ge        , 
    u32_t_mr_ls        , u32_t_mr_le        , u32_t_r_eq         , u32_t_r_ne         , u32_t_r_gt         , u32_t_r_ge         , u32_t_r_ls         , u32_t_r_le         , u32_t_t_eq         , u32_t_t_ne         , 
    u32_t_t_gt         , u32_t_t_ge         , u32_t_t_ls         , u32_t_t_le         , i64_mr_mr_eq       , i64_mr_mr_ne       , i64_mr_mr_gt       , i64_mr_mr_ge       , i64_mr_mr_ls       , i64_mr_mr_le       , 
    i64_mr_r_eq        , i64_mr_r_ne        , i64_mr_r_gt        , i64_mr_r_ge        , i64_mr_r_ls        , i64_mr_r_le        , i64_mr_t_eq        , i64_mr_t_ne        , i64_mr_t_gt        , i64_mr_t_ge        , 
    i64_mr_t_ls        , i64_mr_t_le        , i64_r_mr_eq        , i64_r_mr_ne        , i64_r_mr_gt        , i64_r_mr_ge        , i64_r_mr_ls        , i64_r_mr_le        , i64_r_r_eq         , i64_r_r_ne         , 
    i64_r_r_gt         , i64_r_r_ge         , i64_r_r_ls         , i64_r_r_le         , i64_r_t_eq         , i64_r_t_ne         , i64_r_t_gt         , i64_r_t_ge         , i64_r_t_ls         , i64_r_t_le         , 
    i64_t_mr_eq        , i64_t_mr_ne        , i64_t_mr_gt        , i64_t_mr_ge        , i64_t_mr_ls        , i64_t_mr_le        , i64_t_r_eq         , i64_t_r_ne         , i64_t_r_gt         , i64_t_r_ge         , 
    i64_t_r_ls         , i64_t_r_le         , i64_t_t_eq         , i64_t_t_ne         , i64_t_t_gt         , i64_t_t_ge         , i64_t_t_ls         , i64_t_t_le         , u64_mr_mr_eq       , u64_mr_mr_ne       , 
    u64_mr_mr_gt       , u64_mr_mr_ge       , u64_mr_mr_ls       , u64_mr_mr_le       , u64_mr_r_eq        , u64_mr_r_ne        , u64_mr_r_gt        , u64_mr_r_ge        , u64_mr_r_ls        , u64_mr_r_le        , 
    u64_mr_t_eq        , u64_mr_t_ne        , u64_mr_t_gt        , u64_mr_t_ge        , u64_mr_t_ls        , u64_mr_t_le        , u64_r_mr_eq        , u64_r_mr_ne        , u64_r_mr_gt        , u64_r_mr_ge        , 
    u64_r_mr_ls        , u64_r_mr_le        , u64_r_r_eq         , u64_r_r_ne         , u64_r_r_gt         , u64_r_r_ge         , u64_r_r_ls         , u64_r_r_le         , u64_r_t_eq         , u64_r_t_ne         , 
    u64_r_t_gt         , u64_r_t_ge         , u64_r_t_ls         , u64_r_t_le         , u64_t_mr_eq        , u64_t_mr_ne        , u64_t_mr_gt        , u64_t_mr_ge        , u64_t_mr_ls        , u64_t_mr_le        , 
    u64_t_r_eq         , u64_t_r_ne         , u64_t_r_gt         , u64_t_r_ge         , u64_t_r_ls         , u64_t_r_le         , u64_t_t_eq         , u64_t_t_ne         , u64_t_t_gt         , u64_t_t_ge         , 
    u64_t_t_ls         , u64_t_t_le         , f32_mr_mr_eq       , f32_mr_mr_ne       , f32_mr_mr_gt       , f32_mr_mr_ge       , f32_mr_mr_ls       , f32_mr_mr_le       , f32_mr_r_eq        , f32_mr_r_ne        , 
    f32_mr_r_gt        , f32_mr_r_ge        , f32_mr_r_ls        , f32_mr_r_le        , f32_mr_t_eq        , f32_mr_t_ne        , f32_mr_t_gt        , f32_mr_t_ge        , f32_mr_t_ls        , f32_mr_t_le        , 
    f32_r_mr_eq        , f32_r_mr_ne        , f32_r_mr_gt        , f32_r_mr_ge        , f32_r_mr_ls        , f32_r_mr_le        , f32_r_r_eq         , f32_r_r_ne         , f32_r_r_gt         , f32_r_r_ge         , 
    f32_r_r_ls         , f32_r_r_le         , f32_r_t_eq         , f32_r_t_ne         , f32_r_t_gt         , f32_r_t_ge         , f32_r_t_ls         , f32_r_t_le         , f32_t_mr_eq        , f32_t_mr_ne        , 
    f32_t_mr_gt        , f32_t_mr_ge        , f32_t_mr_ls        , f32_t_mr_le        , f32_t_r_eq         , f32_t_r_ne         , f32_t_r_gt         , f32_t_r_ge         , f32_t_r_ls         , f32_t_r_le         , 
    f32_t_t_eq         , f32_t_t_ne         , f32_t_t_gt         , f32_t_t_ge         , f32_t_t_ls         , f32_t_t_le         , f64_mr_mr_eq       , f64_mr_mr_ne       , f64_mr_mr_gt       , f64_mr_mr_ge       , 
    f64_mr_mr_ls       , f64_mr_mr_le       , f64_mr_r_eq        , f64_mr_r_ne        , f64_mr_r_gt        , f64_mr_r_ge        , f64_mr_r_ls        , f64_mr_r_le        , f64_mr_t_eq        , f64_mr_t_ne        , 
    f64_mr_t_gt        , f64_mr_t_ge        , f64_mr_t_ls        , f64_mr_t_le        , f64_r_mr_eq        , f64_r_mr_ne        , f64_r_mr_gt        , f64_r_mr_ge        , f64_r_mr_ls        , f64_r_mr_le        , 
    f64_r_r_eq         , f64_r_r_ne         , f64_r_r_gt         , f64_r_r_ge         , f64_r_r_ls         , f64_r_r_le         , f64_r_t_eq         , f64_r_t_ne         , f64_r_t_gt         , f64_r_t_ge         , 
    f64_r_t_ls         , f64_r_t_le         , f64_t_mr_eq        , f64_t_mr_ne        , f64_t_mr_gt        , f64_t_mr_ge        , f64_t_mr_ls        , f64_t_mr_le        , f64_t_r_eq         , f64_t_r_ne         , 
    f64_t_r_gt         , f64_t_r_ge         , f64_t_r_ls         , f64_t_r_le         , f64_t_t_eq         , f64_t_t_ne         , f64_t_t_gt         , f64_t_t_ge         , f64_t_t_ls         , f64_t_t_le         , 
    B_mr_mr_eq         , B_mr_mr_ne         , B_mr_mr_gt         , B_mr_mr_ge         , B_mr_mr_ls         , B_mr_mr_le         , B_mr_r_eq          , B_mr_r_ne          , B_mr_r_gt          , B_mr_r_ge          , 
    B_mr_r_ls          , B_mr_r_le          , B_mr_t_eq          , B_mr_t_ne          , B_mr_t_gt          , B_mr_t_ge          , B_mr_t_ls          , B_mr_t_le          , B_r_mr_eq          , B_r_mr_ne          , 
    B_r_mr_gt          , B_r_mr_ge          , B_r_mr_ls          , B_r_mr_le          , B_r_r_eq           , B_r_r_ne           , B_r_r_gt           , B_r_r_ge           , B_r_r_ls           , B_r_r_le           , 
    B_r_t_eq           , B_r_t_ne           , B_r_t_gt           , B_r_t_ge           , B_r_t_ls           , B_r_t_le           , B_t_mr_eq          , B_t_mr_ne          , B_t_mr_gt          , B_t_mr_ge          , 
    B_t_mr_ls          , B_t_mr_le          , B_t_r_eq           , B_t_r_ne           , B_t_r_gt           , B_t_r_ge           , B_t_r_ls           , B_t_r_le           , B_t_t_eq           , B_t_t_ne           , 
    B_t_t_gt           , B_t_t_ge           , B_t_t_ls           , B_t_t_le           , 
    c_c_r_cvt          , c_c_mr_cvt         , c_c_t_cvt          , c_b_r_cvt          , c_b_mr_cvt         , c_b_t_cvt          , c_i16_r_cvt        , c_i16_mr_cvt       , c_i16_t_cvt        , c_u16_r_cvt        , 
    c_u16_mr_cvt       , c_u16_t_cvt        , c_i32_r_cvt        , c_i32_mr_cvt       , c_i32_t_cvt        , c_u32_r_cvt        , c_u32_mr_cvt       , c_u32_t_cvt        , c_i64_r_cvt        , c_i64_mr_cvt       , 
    c_i64_t_cvt        , c_u64_r_cvt        , c_u64_mr_cvt       , c_u64_t_cvt        , c_f32_r_cvt        , c_f32_mr_cvt       , c_f32_t_cvt        , c_f64_r_cvt        , c_f64_mr_cvt       , c_f64_t_cvt        , 
    c_B_r_cvt          , c_B_mr_cvt         , c_B_t_cvt          , b_c_r_cvt          , b_c_mr_cvt         , b_c_t_cvt          , b_b_r_cvt          , b_b_mr_cvt         , b_b_t_cvt          , b_i16_r_cvt        , 
    b_i16_mr_cvt       , b_i16_t_cvt        , b_u16_r_cvt        , b_u16_mr_cvt       , b_u16_t_cvt        , b_i32_r_cvt        , b_i32_mr_cvt       , b_i32_t_cvt        , b_u32_r_cvt        , b_u32_mr_cvt       , 
    b_u32_t_cvt        , b_i64_r_cvt        , b_i64_mr_cvt       , b_i64_t_cvt        , b_u64_r_cvt        , b_u64_mr_cvt       , b_u64_t_cvt        , b_f32_r_cvt        , b_f32_mr_cvt       , b_f32_t_cvt        , 
    b_f64_r_cvt        , b_f64_mr_cvt       , b_f64_t_cvt        , b_B_r_cvt          , b_B_mr_cvt         , b_B_t_cvt          , i16_c_r_cvt        , i16_c_mr_cvt       , i16_c_t_cvt        , i16_b_r_cvt        , 
    i16_b_mr_cvt       , i16_b_t_cvt        , i16_i16_r_cvt      , i16_i16_mr_cvt     , i16_i16_t_cvt      , i16_u16_r_cvt      , i16_u16_mr_cvt     , i16_u16_t_cvt      , i16_i32_r_cvt      , i16_i32_mr_cvt     , 
    i16_i32_t_cvt      , i16_u32_r_cvt      , i16_u32_mr_cvt     , i16_u32_t_cvt      , i16_i64_r_cvt      , i16_i64_mr_cvt     , i16_i64_t_cvt      , i16_u64_r_cvt      , i16_u64_mr_cvt     , i16_u64_t_cvt      , 
    i16_f32_r_cvt      , i16_f32_mr_cvt     , i16_f32_t_cvt      , i16_f64_r_cvt      , i16_f64_mr_cvt     , i16_f64_t_cvt      , i16_B_r_cvt        , i16_B_mr_cvt       , i16_B_t_cvt        , u16_c_r_cvt        , 
    u16_c_mr_cvt       , u16_c_t_cvt        , u16_b_r_cvt        , u16_b_mr_cvt       , u16_b_t_cvt        , u16_i16_r_cvt      , u16_i16_mr_cvt     , u16_i16_t_cvt      , u16_u16_r_cvt      , u16_u16_mr_cvt     , 
    u16_u16_t_cvt      , u16_i32_r_cvt      , u16_i32_mr_cvt     , u16_i32_t_cvt      , u16_u32_r_cvt      , u16_u32_mr_cvt     , u16_u32_t_cvt      , u16_i64_r_cvt      , u16_i64_mr_cvt     , u16_i64_t_cvt      , 
    u16_u64_r_cvt      , u16_u64_mr_cvt     , u16_u64_t_cvt      , u16_f32_r_cvt      , u16_f32_mr_cvt     , u16_f32_t_cvt      , u16_f64_r_cvt      , u16_f64_mr_cvt     , u16_f64_t_cvt      , u16_B_r_cvt        , 
    u16_B_mr_cvt       , u16_B_t_cvt        , i32_c_r_cvt        , i32_c_mr_cvt       , i32_c_t_cvt        , i32_b_r_cvt        , i32_b_mr_cvt       , i32_b_t_cvt        , i32_i16_r_cvt      , i32_i16_mr_cvt     , 
    i32_i16_t_cvt      , i32_u16_r_cvt      , i32_u16_mr_cvt     , i32_u16_t_cvt      , i32_i32_r_cvt      , i32_i32_mr_cvt     , i32_i32_t_cvt      , i32_u32_r_cvt      , i32_u32_mr_cvt     , i32_u32_t_cvt      , 
    i32_i64_r_cvt      , i32_i64_mr_cvt     , i32_i64_t_cvt      , i32_u64_r_cvt      , i32_u64_mr_cvt     , i32_u64_t_cvt      , i32_f32_r_cvt      , i32_f32_mr_cvt     , i32_f32_t_cvt      , i32_f64_r_cvt      , 
    i32_f64_mr_cvt     , i32_f64_t_cvt      , i32_B_r_cvt        , i32_B_mr_cvt       , i32_B_t_cvt        , u32_c_r_cvt        , u32_c_mr_cvt       , u32_c_t_cvt        , u32_b_r_cvt        , u32_b_mr_cvt       , 
    u32_b_t_cvt        , u32_i16_r_cvt      , u32_i16_mr_cvt     , u32_i16_t_cvt      , u32_u16_r_cvt      , u32_u16_mr_cvt     , u32_u16_t_cvt      , u32_i32_r_cvt      , u32_i32_mr_cvt     , u32_i32_t_cvt      , 
    u32_u32_r_cvt      , u32_u32_mr_cvt     , u32_u32_t_cvt      , u32_i64_r_cvt      , u32_i64_mr_cvt     , u32_i64_t_cvt      , u32_u64_r_cvt      , u32_u64_mr_cvt     , u32_u64_t_cvt      , u32_f32_r_cvt      , 
    u32_f32_mr_cvt     , u32_f32_t_cvt      , u32_f64_r_cvt      , u32_f64_mr_cvt     , u32_f64_t_cvt      , u32_B_r_cvt        , u32_B_mr_cvt       , u32_B_t_cvt        , i64_c_r_cvt        , i64_c_mr_cvt       , 
    i64_c_t_cvt        , i64_b_r_cvt        , i64_b_mr_cvt       , i64_b_t_cvt        , i64_i16_r_cvt      , i64_i16_mr_cvt     , i64_i16_t_cvt      , i64_u16_r_cvt      , i64_u16_mr_cvt     , i64_u16_t_cvt      , 
    i64_i32_r_cvt      , i64_i32_mr_cvt     , i64_i32_t_cvt      , i64_u32_r_cvt      , i64_u32_mr_cvt     , i64_u32_t_cvt      , i64_i64_r_cvt      , i64_i64_mr_cvt     , i64_i64_t_cvt      , i64_u64_r_cvt      , 
    i64_u64_mr_cvt     , i64_u64_t_cvt      , i64_f32_r_cvt      , i64_f32_mr_cvt     , i64_f32_t_cvt      , i64_f64_r_cvt      , i64_f64_mr_cvt     , i64_f64_t_cvt      , i64_B_r_cvt        , i64_B_mr_cvt       , 
    i64_B_t_cvt        , u64_c_r_cvt        , u64_c_mr_cvt       , u64_c_t_cvt        , u64_b_r_cvt        , u64_b_mr_cvt       , u64_b_t_cvt        , u64_i16_r_cvt      , u64_i16_mr_cvt     , u64_i16_t_cvt      , 
    u64_u16_r_cvt      , u64_u16_mr_cvt     , u64_u16_t_cvt      , u64_i32_r_cvt      , u64_i32_mr_cvt     , u64_i32_t_cvt      , u64_u32_r_cvt      , u64_u32_mr_cvt     , u64_u32_t_cvt      , u64_i64_r_cvt      , 
    u64_i64_mr_cvt     , u64_i64_t_cvt      , u64_u64_r_cvt      , u64_u64_mr_cvt     , u64_u64_t_cvt      , u64_f32_r_cvt      , u64_f32_mr_cvt     , u64_f32_t_cvt      , u64_f64_r_cvt      , u64_f64_mr_cvt     , 
    u64_f64_t_cvt      , u64_B_r_cvt        , u64_B_mr_cvt       , u64_B_t_cvt        , f32_c_r_cvt        , f32_c_mr_cvt       , f32_c_t_cvt        , f32_b_r_cvt        , f32_b_mr_cvt       , f32_b_t_cvt        , 
    f32_i16_r_cvt      , f32_i16_mr_cvt     , f32_i16_t_cvt      , f32_u16_r_cvt      , f32_u16_mr_cvt     , f32_u16_t_cvt      , f32_i32_r_cvt      , f32_i32_mr_cvt     , f32_i32_t_cvt      , f32_u32_r_cvt      , 
    f32_u32_mr_cvt     , f32_u32_t_cvt      , f32_i64_r_cvt      , f32_i64_mr_cvt     , f32_i64_t_cvt      , f32_u64_r_cvt      , f32_u64_mr_cvt     , f32_u64_t_cvt      , f32_f32_r_cvt      , f32_f32_mr_cvt     , 
    f32_f32_t_cvt      , f32_f64_r_cvt      , f32_f64_mr_cvt     , f32_f64_t_cvt      , f32_B_r_cvt        , f32_B_mr_cvt       , f32_B_t_cvt        , f64_c_r_cvt        , f64_c_mr_cvt       , f64_c_t_cvt        , 
    f64_b_r_cvt        , f64_b_mr_cvt       , f64_b_t_cvt        , f64_i16_r_cvt      , f64_i16_mr_cvt     , f64_i16_t_cvt      , f64_u16_r_cvt      , f64_u16_mr_cvt     , f64_u16_t_cvt      , f64_i32_r_cvt      , 
    f64_i32_mr_cvt     , f64_i32_t_cvt      , f64_u32_r_cvt      , f64_u32_mr_cvt     , f64_u32_t_cvt      , f64_i64_r_cvt      , f64_i64_mr_cvt     , f64_i64_t_cvt      , f64_u64_r_cvt      , f64_u64_mr_cvt     , 
    f64_u64_t_cvt      , f64_f32_r_cvt      , f64_f32_mr_cvt     , f64_f32_t_cvt      , f64_f64_r_cvt      , f64_f64_mr_cvt     , f64_f64_t_cvt      , f64_B_r_cvt        , f64_B_mr_cvt       , f64_B_t_cvt        , 
    B_c_r_cvt          , B_c_mr_cvt         , B_c_t_cvt          , B_b_r_cvt          , B_b_mr_cvt         , B_b_t_cvt          , B_i16_r_cvt        , B_i16_mr_cvt       , B_i16_t_cvt        , B_u16_r_cvt        , 
    B_u16_mr_cvt       , B_u16_t_cvt        , B_i32_r_cvt        , B_i32_mr_cvt       , B_i32_t_cvt        , B_u32_r_cvt        , B_u32_mr_cvt       , B_u32_t_cvt        , B_i64_r_cvt        , B_i64_mr_cvt       , 
    B_i64_t_cvt        , B_u64_r_cvt        , B_u64_mr_cvt       , B_u64_t_cvt        , B_f32_r_cvt        , B_f32_mr_cvt       , B_f32_t_cvt        , B_f64_r_cvt        , B_f64_mr_cvt       , B_f64_t_cvt        , 
    B_B_r_cvt          , B_B_mr_cvt         , B_B_t_cvt          , 
    c_r_pop            , c_mr_pop           , c_t_pop            , b_r_pop            , b_mr_pop           , b_t_pop            , i16_r_pop          , i16_mr_pop         , i16_t_pop          , u16_r_pop          , 
    u16_mr_pop         , u16_t_pop          , i32_r_pop          , i32_mr_pop         , i32_t_pop          , u32_r_pop          , u32_mr_pop         , u32_t_pop          , i64_r_pop          , i64_mr_pop         , 
    i64_t_pop          , u64_r_pop          , u64_mr_pop         , u64_t_pop          , f32_r_pop          , f32_mr_pop         , f32_t_pop          , f64_r_pop          , f64_mr_pop         , f64_t_pop          , 
    o_r_pop            , o_mr_pop           , o_t_pop            , B_r_pop            , B_mr_pop           , B_t_pop            , 
    c_push             , b_push             , i16_push           , u16_push           , i32_push           , u32_push           , i64_push           , u64_push           , f32_push           , f64_push           , 

    c_pvar             , b_pvar             , i16_pvar           , u16_pvar           , i32_pvar           , u32_pvar           , i64_pvar           , u64_pvar           , f32_pvar           , f64_pvar           , 
    o_pvar             , B_pvar             , 
    c_pglo             , b_pglo             , i16_pglo           , u16_pglo           , i32_pglo           , u32_pglo           , i64_pglo           , u64_pglo           , f32_pglo           , f64_pglo           , 
    o_pglo             , B_pglo             , 
    c_cpy              , b_cpy              , i16_cpy            , u16_cpy            , i32_cpy            , u32_cpy            , i64_cpy            , u64_cpy            , f32_cpy            , f64_cpy            , 
    o_cpy              , B_cpy              , 
    setlocal           , 
    getarg             , 
    _new               , 
    arrnew             , 
    c_mr_gvl           , c_r_gvl            , b_mr_gvl           , b_r_gvl            , i16_mr_gvl         , i16_r_gvl          , u16_mr_gvl         , u16_r_gvl          , i32_mr_gvl         , i32_r_gvl          , 
    u32_mr_gvl         , u32_r_gvl          , i64_mr_gvl         , i64_r_gvl          , u64_mr_gvl         , u64_r_gvl          , f32_mr_gvl         , f32_r_gvl          , f64_mr_gvl         , f64_r_gvl          , 
    o_mr_gvl           , o_r_gvl            , B_mr_gvl           , B_r_gvl            , 
    c_mr_mem           , c_r_mem            , c_t_mem            , b_mr_mem           , b_r_mem            , b_t_mem            , i16_mr_mem         , i16_r_mem          , i16_t_mem          , u16_mr_mem         , 
    u16_r_mem          , u16_t_mem          , i32_mr_mem         , i32_r_mem          , i32_t_mem          , u32_mr_mem         , u32_r_mem          , u32_t_mem          , i64_mr_mem         , i64_r_mem          , 
    i64_t_mem          , u64_mr_mem         , u64_r_mem          , u64_t_mem          , f32_mr_mem         , f32_r_mem          , f32_t_mem          , f64_mr_mem         , f64_r_mem          , f64_t_mem          , 
    o_mr_mem           , o_r_mem            , o_t_mem            , B_mr_mem           , B_r_mem            , B_t_mem            , 
    c_mr_vmem          , c_r_vmem           , c_t_vmem           , b_mr_vmem          , b_r_vmem           , b_t_vmem           , i16_mr_vmem        , i16_r_vmem         , i16_t_vmem         , u16_mr_vmem        , 
    u16_r_vmem         , u16_t_vmem         , i32_mr_vmem        , i32_r_vmem         , i32_t_vmem         , u32_mr_vmem        , u32_r_vmem         , u32_t_vmem         , i64_mr_vmem        , i64_r_vmem         , 
    i64_t_vmem         , u64_mr_vmem        , u64_r_vmem         , u64_t_vmem         , f32_mr_vmem        , f32_r_vmem         , f32_t_vmem         , f64_mr_vmem        , f64_r_vmem         , f64_t_vmem         , 
    o_mr_vmem          , o_r_vmem           , o_t_vmem           , B_mr_vmem          , B_r_vmem           , B_t_vmem           , 
    c_mr_arrmem        , c_r_arrmem         , c_t_arrmem         , b_mr_arrmem        , b_r_arrmem         , b_t_arrmem         , i16_mr_arrmem      , i16_r_arrmem       , i16_t_arrmem       , u16_mr_arrmem      , 
    u16_r_arrmem       , u16_t_arrmem       , i32_mr_arrmem      , i32_r_arrmem       , i32_t_arrmem       , u32_mr_arrmem      , u32_r_arrmem       , u32_t_arrmem       , i64_mr_arrmem      , i64_r_arrmem       , 
    i64_t_arrmem       , u64_mr_arrmem      , u64_r_arrmem       , u64_t_arrmem       , f32_mr_arrmem      , f32_r_arrmem       , f32_t_arrmem       , f64_mr_arrmem      , f64_r_arrmem       , f64_t_arrmem       , 
    o_mr_arrmem        , o_r_arrmem         , o_t_arrmem         , B_mr_arrmem        , B_r_arrmem         , B_t_arrmem         , 
    call               , 
    mr_vcall           , r_vcall            , t_vcall            , 
    jmp                , 
    r_jz               , r_jp               , mr_jz              , mr_jp              , t_jz               , t_jp               , 
    setarg             , 
    ret                , 
    vret               , 
    catostr            , 
    strtoca            , 
    getcls             , 
    getmtds            , 
    getflds            , 
    getctrs            , 
    sys                ,
    setgtbl            ,
    getgtbl            ,
    unknown
};

enum class TCommand {
    none      , mov       , addmov    , submov    , mulmov    , divmov    , andmov    , ormov     , xormov    , shlmov    , 
    shrmov    , modmov    , add       , sub       , mul       , div       , _and      , _or       , _xor      , shl       , 
    shr       , mod       , _not      , pinc      , sinc      , pdec      , sdec      , eq        , ne        , gt        , 
    ge        , ls        , le        , cvt       , pop       , push      , pvar      , pglo      , cpy       , setlocal  , 
    getarg    , _new      , arrnew    , gvl       , mem       , vmem      , arrmem    , call      , vcall     , jmp       , 
    jz        , jp        , setarg    , ret       , vret      , catostr   , strtoca   , getcls    , getmtds   , getflds   , 
    getctrs   , sys       , setgtbl   , getgtbl   ,
    unknown,
};


enum class PretreatCommand {
    RELY, EXTERN, EXPOSE, LABEL, GLOMEM, HINT, STRING, DEF, unknown,
};

extern const int commandNumber;
extern const std::string commandString[];

extern const int tCommandNumber;
extern const std::string tCommandString[];

extern const int pretreatCommandNumber;
extern const std::string pretreatCommandString[];

Command getCommand(const std::string &name);
TCommand getTCommand(const std::string &name);
PretreatCommand getPretreatCommand(const std::string &name);

Command wrap(TCommand tcmd, DataTypeModifier dtMdf);
Command wrap(TCommand tcmd,  DataTypeModifier dtMdf, ValueTypeModifier vlMdf);
Command wrap(TCommand tcmd, DataTypeModifier dtMdf, ValueTypeModifier vtMdf1, ValueTypeModifier vtMdf2);
Command wrap(TCommand tcmd,  DataTypeModifier dtMdf1, DataTypeModifier dtMdf2, ValueTypeModifier vtMdf);