#include "commandlist.h"

const std::string commandString[] = {
    "none", 
    "c_mr_mr_mov"       , "c_mr_r_mov"        , "c_mr_t_mov"        , "c_r_mr_mov"        , "c_r_r_mov"         , "c_r_t_mov"         , "b_mr_mr_mov"       , "b_mr_r_mov"        , "b_mr_t_mov"        , "b_r_mr_mov"        , 
    "b_r_r_mov"         , "b_r_t_mov"         , "i16_mr_mr_mov"     , "i16_mr_r_mov"      , "i16_mr_t_mov"      , "i16_r_mr_mov"      , "i16_r_r_mov"       , "i16_r_t_mov"       , "u16_mr_mr_mov"     , "u16_mr_r_mov"      , 
    "u16_mr_t_mov"      , "u16_r_mr_mov"      , "u16_r_r_mov"       , "u16_r_t_mov"       , "i32_mr_mr_mov"     , "i32_mr_r_mov"      , "i32_mr_t_mov"      , "i32_r_mr_mov"      , "i32_r_r_mov"       , "i32_r_t_mov"       , 
    "u32_mr_mr_mov"     , "u32_mr_r_mov"      , "u32_mr_t_mov"      , "u32_r_mr_mov"      , "u32_r_r_mov"       , "u32_r_t_mov"       , "i64_mr_mr_mov"     , "i64_mr_r_mov"      , "i64_mr_t_mov"      , "i64_r_mr_mov"      , 
    "i64_r_r_mov"       , "i64_r_t_mov"       , "u64_mr_mr_mov"     , "u64_mr_r_mov"      , "u64_mr_t_mov"      , "u64_r_mr_mov"      , "u64_r_r_mov"       , "u64_r_t_mov"       , "f32_mr_mr_mov"     , "f32_mr_r_mov"      , 
    "f32_mr_t_mov"      , "f32_r_mr_mov"      , "f32_r_r_mov"       , "f32_r_t_mov"       , "f64_mr_mr_mov"     , "f64_mr_r_mov"      , "f64_mr_t_mov"      , "f64_r_mr_mov"      , "f64_r_r_mov"       , "f64_r_t_mov"       , 
    "o_mr_mr_mov"       , "o_mr_r_mov"        , "o_mr_t_mov"        , "o_r_mr_mov"        , "o_r_r_mov"         , "o_r_t_mov"         , "B_mr_mr_mov"       , "B_mr_r_mov"        , "B_mr_t_mov"        , "B_r_mr_mov"        , 
    "B_r_r_mov"         , "B_r_t_mov"         , 
    "c_r_mr_add_mov"    , "c_r_mr_sub_mov"    , "c_r_mr_mul_mov"    , "c_r_mr_div_mov"    , "c_r_r_add_mov"     , "c_r_r_sub_mov"     , "c_r_r_mul_mov"     , "c_r_r_div_mov"     , 
    "c_r_t_add_mov"     , "c_r_t_sub_mov"     , "c_r_t_mul_mov"     , "c_r_t_div_mov"     , "c_mr_mr_add_mov"   , "c_mr_mr_sub_mov"   , "c_mr_mr_mul_mov"   , "c_mr_mr_div_mov"   , "c_mr_r_add_mov"    , "c_mr_r_sub_mov"    , 
    "c_mr_r_mul_mov"    , "c_mr_r_div_mov"    , "c_mr_t_add_mov"    , "c_mr_t_sub_mov"    , "c_mr_t_mul_mov"    , "c_mr_t_div_mov"    , "b_r_mr_add_mov"    , "b_r_mr_sub_mov"    , "b_r_mr_mul_mov"    , "b_r_mr_div_mov"    , 
    "b_r_r_add_mov"     , "b_r_r_sub_mov"     , "b_r_r_mul_mov"     , "b_r_r_div_mov"     , "b_r_t_add_mov"     , "b_r_t_sub_mov"     , "b_r_t_mul_mov"     , "b_r_t_div_mov"     , "b_mr_mr_add_mov"   , "b_mr_mr_sub_mov"   , 
    "b_mr_mr_mul_mov"   , "b_mr_mr_div_mov"   , "b_mr_r_add_mov"    , "b_mr_r_sub_mov"    , "b_mr_r_mul_mov"    , "b_mr_r_div_mov"    , "b_mr_t_add_mov"    , "b_mr_t_sub_mov"    , "b_mr_t_mul_mov"    , "b_mr_t_div_mov"    , 
    "i16_r_mr_add_mov"  , "i16_r_mr_sub_mov"  , "i16_r_mr_mul_mov"  , "i16_r_mr_div_mov"  , "i16_r_r_add_mov"   , "i16_r_r_sub_mov"   , "i16_r_r_mul_mov"   , "i16_r_r_div_mov"   , "i16_r_t_add_mov"   , "i16_r_t_sub_mov"   , 
    "i16_r_t_mul_mov"   , "i16_r_t_div_mov"   , "i16_mr_mr_add_mov" , "i16_mr_mr_sub_mov" , "i16_mr_mr_mul_mov" , "i16_mr_mr_div_mov" , "i16_mr_r_add_mov"  , "i16_mr_r_sub_mov"  , "i16_mr_r_mul_mov"  , "i16_mr_r_div_mov"  , 
    "i16_mr_t_add_mov"  , "i16_mr_t_sub_mov"  , "i16_mr_t_mul_mov"  , "i16_mr_t_div_mov"  , "u16_r_mr_add_mov"  , "u16_r_mr_sub_mov"  , "u16_r_mr_mul_mov"  , "u16_r_mr_div_mov"  , "u16_r_r_add_mov"   , "u16_r_r_sub_mov"   , 
    "u16_r_r_mul_mov"   , "u16_r_r_div_mov"   , "u16_r_t_add_mov"   , "u16_r_t_sub_mov"   , "u16_r_t_mul_mov"   , "u16_r_t_div_mov"   , "u16_mr_mr_add_mov" , "u16_mr_mr_sub_mov" , "u16_mr_mr_mul_mov" , "u16_mr_mr_div_mov" , 
    "u16_mr_r_add_mov"  , "u16_mr_r_sub_mov"  , "u16_mr_r_mul_mov"  , "u16_mr_r_div_mov"  , "u16_mr_t_add_mov"  , "u16_mr_t_sub_mov"  , "u16_mr_t_mul_mov"  , "u16_mr_t_div_mov"  , "i32_r_mr_add_mov"  , "i32_r_mr_sub_mov"  , 
    "i32_r_mr_mul_mov"  , "i32_r_mr_div_mov"  , "i32_r_r_add_mov"   , "i32_r_r_sub_mov"   , "i32_r_r_mul_mov"   , "i32_r_r_div_mov"   , "i32_r_t_add_mov"   , "i32_r_t_sub_mov"   , "i32_r_t_mul_mov"   , "i32_r_t_div_mov"   , 
    "i32_mr_mr_add_mov" , "i32_mr_mr_sub_mov" , "i32_mr_mr_mul_mov" , "i32_mr_mr_div_mov" , "i32_mr_r_add_mov"  , "i32_mr_r_sub_mov"  , "i32_mr_r_mul_mov"  , "i32_mr_r_div_mov"  , "i32_mr_t_add_mov"  , "i32_mr_t_sub_mov"  , 
    "i32_mr_t_mul_mov"  , "i32_mr_t_div_mov"  , "u32_r_mr_add_mov"  , "u32_r_mr_sub_mov"  , "u32_r_mr_mul_mov"  , "u32_r_mr_div_mov"  , "u32_r_r_add_mov"   , "u32_r_r_sub_mov"   , "u32_r_r_mul_mov"   , "u32_r_r_div_mov"   , 
    "u32_r_t_add_mov"   , "u32_r_t_sub_mov"   , "u32_r_t_mul_mov"   , "u32_r_t_div_mov"   , "u32_mr_mr_add_mov" , "u32_mr_mr_sub_mov" , "u32_mr_mr_mul_mov" , "u32_mr_mr_div_mov" , "u32_mr_r_add_mov"  , "u32_mr_r_sub_mov"  , 
    "u32_mr_r_mul_mov"  , "u32_mr_r_div_mov"  , "u32_mr_t_add_mov"  , "u32_mr_t_sub_mov"  , "u32_mr_t_mul_mov"  , "u32_mr_t_div_mov"  , "i64_r_mr_add_mov"  , "i64_r_mr_sub_mov"  , "i64_r_mr_mul_mov"  , "i64_r_mr_div_mov"  , 
    "i64_r_r_add_mov"   , "i64_r_r_sub_mov"   , "i64_r_r_mul_mov"   , "i64_r_r_div_mov"   , "i64_r_t_add_mov"   , "i64_r_t_sub_mov"   , "i64_r_t_mul_mov"   , "i64_r_t_div_mov"   , "i64_mr_mr_add_mov" , "i64_mr_mr_sub_mov" , 
    "i64_mr_mr_mul_mov" , "i64_mr_mr_div_mov" , "i64_mr_r_add_mov"  , "i64_mr_r_sub_mov"  , "i64_mr_r_mul_mov"  , "i64_mr_r_div_mov"  , "i64_mr_t_add_mov"  , "i64_mr_t_sub_mov"  , "i64_mr_t_mul_mov"  , "i64_mr_t_div_mov"  , 
    "u64_r_mr_add_mov"  , "u64_r_mr_sub_mov"  , "u64_r_mr_mul_mov"  , "u64_r_mr_div_mov"  , "u64_r_r_add_mov"   , "u64_r_r_sub_mov"   , "u64_r_r_mul_mov"   , "u64_r_r_div_mov"   , "u64_r_t_add_mov"   , "u64_r_t_sub_mov"   , 
    "u64_r_t_mul_mov"   , "u64_r_t_div_mov"   , "u64_mr_mr_add_mov" , "u64_mr_mr_sub_mov" , "u64_mr_mr_mul_mov" , "u64_mr_mr_div_mov" , "u64_mr_r_add_mov"  , "u64_mr_r_sub_mov"  , "u64_mr_r_mul_mov"  , "u64_mr_r_div_mov"  , 
    "u64_mr_t_add_mov"  , "u64_mr_t_sub_mov"  , "u64_mr_t_mul_mov"  , "u64_mr_t_div_mov"  , "f32_r_mr_add_mov"  , "f32_r_mr_sub_mov"  , "f32_r_mr_mul_mov"  , "f32_r_mr_div_mov"  , "f32_r_r_add_mov"   , "f32_r_r_sub_mov"   , 
    "f32_r_r_mul_mov"   , "f32_r_r_div_mov"   , "f32_r_t_add_mov"   , "f32_r_t_sub_mov"   , "f32_r_t_mul_mov"   , "f32_r_t_div_mov"   , "f32_mr_mr_add_mov" , "f32_mr_mr_sub_mov" , "f32_mr_mr_mul_mov" , "f32_mr_mr_div_mov" , 
    "f32_mr_r_add_mov"  , "f32_mr_r_sub_mov"  , "f32_mr_r_mul_mov"  , "f32_mr_r_div_mov"  , "f32_mr_t_add_mov"  , "f32_mr_t_sub_mov"  , "f32_mr_t_mul_mov"  , "f32_mr_t_div_mov"  , "f64_r_mr_add_mov"  , "f64_r_mr_sub_mov"  , 
    "f64_r_mr_mul_mov"  , "f64_r_mr_div_mov"  , "f64_r_r_add_mov"   , "f64_r_r_sub_mov"   , "f64_r_r_mul_mov"   , "f64_r_r_div_mov"   , "f64_r_t_add_mov"   , "f64_r_t_sub_mov"   , "f64_r_t_mul_mov"   , "f64_r_t_div_mov"   , 
    "f64_mr_mr_add_mov" , "f64_mr_mr_sub_mov" , "f64_mr_mr_mul_mov" , "f64_mr_mr_div_mov" , "f64_mr_r_add_mov"  , "f64_mr_r_sub_mov"  , "f64_mr_r_mul_mov"  , "f64_mr_r_div_mov"  , "f64_mr_t_add_mov"  , "f64_mr_t_sub_mov"  , 
    "f64_mr_t_mul_mov"  , "f64_mr_t_div_mov"  , "B_r_mr_add_mov"    , "B_r_mr_sub_mov"    , "B_r_mr_mul_mov"    , "B_r_mr_div_mov"    , "B_r_r_add_mov"     , "B_r_r_sub_mov"     , "B_r_r_mul_mov"     , "B_r_r_div_mov"     , 
    "B_r_t_add_mov"     , "B_r_t_sub_mov"     , "B_r_t_mul_mov"     , "B_r_t_div_mov"     , "B_mr_mr_add_mov"   , "B_mr_mr_sub_mov"   , "B_mr_mr_mul_mov"   , "B_mr_mr_div_mov"   , "B_mr_r_add_mov"    , "B_mr_r_sub_mov"    , 
    "B_mr_r_mul_mov"    , "B_mr_r_div_mov"    , "B_mr_t_add_mov"    , "B_mr_t_sub_mov"    , "B_mr_t_mul_mov"    , "B_mr_t_div_mov"    , 
    "c_r_mr_and_mov"    , "c_r_mr_or_mov"     , "c_r_mr_xor_mov"    , "c_r_mr_shl_mov"    , 
    "c_r_mr_shr_mov"    , "c_r_mr_mod_mov"    , "c_r_r_and_mov"     , "c_r_r_or_mov"      , "c_r_r_xor_mov"     , "c_r_r_shl_mov"     , "c_r_r_shr_mov"     , "c_r_r_mod_mov"     , "c_r_t_and_mov"     , "c_r_t_or_mov"      , 
    "c_r_t_xor_mov"     , "c_r_t_shl_mov"     , "c_r_t_shr_mov"     , "c_r_t_mod_mov"     , "c_mr_mr_and_mov"   , "c_mr_mr_or_mov"    , "c_mr_mr_xor_mov"   , "c_mr_mr_shl_mov"   , "c_mr_mr_shr_mov"   , "c_mr_mr_mod_mov"   , 
    "c_mr_r_and_mov"    , "c_mr_r_or_mov"     , "c_mr_r_xor_mov"    , "c_mr_r_shl_mov"    , "c_mr_r_shr_mov"    , "c_mr_r_mod_mov"    , "c_mr_t_and_mov"    , "c_mr_t_or_mov"     , "c_mr_t_xor_mov"    , "c_mr_t_shl_mov"    , 
    "c_mr_t_shr_mov"    , "c_mr_t_mod_mov"    , "b_r_mr_and_mov"    , "b_r_mr_or_mov"     , "b_r_mr_xor_mov"    , "b_r_mr_shl_mov"    , "b_r_mr_shr_mov"    , "b_r_mr_mod_mov"    , "b_r_r_and_mov"     , "b_r_r_or_mov"      , 
    "b_r_r_xor_mov"     , "b_r_r_shl_mov"     , "b_r_r_shr_mov"     , "b_r_r_mod_mov"     , "b_r_t_and_mov"     , "b_r_t_or_mov"      , "b_r_t_xor_mov"     , "b_r_t_shl_mov"     , "b_r_t_shr_mov"     , "b_r_t_mod_mov"     , 
    "b_mr_mr_and_mov"   , "b_mr_mr_or_mov"    , "b_mr_mr_xor_mov"   , "b_mr_mr_shl_mov"   , "b_mr_mr_shr_mov"   , "b_mr_mr_mod_mov"   , "b_mr_r_and_mov"    , "b_mr_r_or_mov"     , "b_mr_r_xor_mov"    , "b_mr_r_shl_mov"    , 
    "b_mr_r_shr_mov"    , "b_mr_r_mod_mov"    , "b_mr_t_and_mov"    , "b_mr_t_or_mov"     , "b_mr_t_xor_mov"    , "b_mr_t_shl_mov"    , "b_mr_t_shr_mov"    , "b_mr_t_mod_mov"    , "i16_r_mr_and_mov"  , "i16_r_mr_or_mov"   , 
    "i16_r_mr_xor_mov"  , "i16_r_mr_shl_mov"  , "i16_r_mr_shr_mov"  , "i16_r_mr_mod_mov"  , "i16_r_r_and_mov"   , "i16_r_r_or_mov"    , "i16_r_r_xor_mov"   , "i16_r_r_shl_mov"   , "i16_r_r_shr_mov"   , "i16_r_r_mod_mov"   , 
    "i16_r_t_and_mov"   , "i16_r_t_or_mov"    , "i16_r_t_xor_mov"   , "i16_r_t_shl_mov"   , "i16_r_t_shr_mov"   , "i16_r_t_mod_mov"   , "i16_mr_mr_and_mov" , "i16_mr_mr_or_mov"  , "i16_mr_mr_xor_mov" , "i16_mr_mr_shl_mov" , 
    "i16_mr_mr_shr_mov" , "i16_mr_mr_mod_mov" , "i16_mr_r_and_mov"  , "i16_mr_r_or_mov"   , "i16_mr_r_xor_mov"  , "i16_mr_r_shl_mov"  , "i16_mr_r_shr_mov"  , "i16_mr_r_mod_mov"  , "i16_mr_t_and_mov"  , "i16_mr_t_or_mov"   , 
    "i16_mr_t_xor_mov"  , "i16_mr_t_shl_mov"  , "i16_mr_t_shr_mov"  , "i16_mr_t_mod_mov"  , "u16_r_mr_and_mov"  , "u16_r_mr_or_mov"   , "u16_r_mr_xor_mov"  , "u16_r_mr_shl_mov"  , "u16_r_mr_shr_mov"  , "u16_r_mr_mod_mov"  , 
    "u16_r_r_and_mov"   , "u16_r_r_or_mov"    , "u16_r_r_xor_mov"   , "u16_r_r_shl_mov"   , "u16_r_r_shr_mov"   , "u16_r_r_mod_mov"   , "u16_r_t_and_mov"   , "u16_r_t_or_mov"    , "u16_r_t_xor_mov"   , "u16_r_t_shl_mov"   , 
    "u16_r_t_shr_mov"   , "u16_r_t_mod_mov"   , "u16_mr_mr_and_mov" , "u16_mr_mr_or_mov"  , "u16_mr_mr_xor_mov" , "u16_mr_mr_shl_mov" , "u16_mr_mr_shr_mov" , "u16_mr_mr_mod_mov" , "u16_mr_r_and_mov"  , "u16_mr_r_or_mov"   , 
    "u16_mr_r_xor_mov"  , "u16_mr_r_shl_mov"  , "u16_mr_r_shr_mov"  , "u16_mr_r_mod_mov"  , "u16_mr_t_and_mov"  , "u16_mr_t_or_mov"   , "u16_mr_t_xor_mov"  , "u16_mr_t_shl_mov"  , "u16_mr_t_shr_mov"  , "u16_mr_t_mod_mov"  , 
    "i32_r_mr_and_mov"  , "i32_r_mr_or_mov"   , "i32_r_mr_xor_mov"  , "i32_r_mr_shl_mov"  , "i32_r_mr_shr_mov"  , "i32_r_mr_mod_mov"  , "i32_r_r_and_mov"   , "i32_r_r_or_mov"    , "i32_r_r_xor_mov"   , "i32_r_r_shl_mov"   , 
    "i32_r_r_shr_mov"   , "i32_r_r_mod_mov"   , "i32_r_t_and_mov"   , "i32_r_t_or_mov"    , "i32_r_t_xor_mov"   , "i32_r_t_shl_mov"   , "i32_r_t_shr_mov"   , "i32_r_t_mod_mov"   , "i32_mr_mr_and_mov" , "i32_mr_mr_or_mov"  , 
    "i32_mr_mr_xor_mov" , "i32_mr_mr_shl_mov" , "i32_mr_mr_shr_mov" , "i32_mr_mr_mod_mov" , "i32_mr_r_and_mov"  , "i32_mr_r_or_mov"   , "i32_mr_r_xor_mov"  , "i32_mr_r_shl_mov"  , "i32_mr_r_shr_mov"  , "i32_mr_r_mod_mov"  , 
    "i32_mr_t_and_mov"  , "i32_mr_t_or_mov"   , "i32_mr_t_xor_mov"  , "i32_mr_t_shl_mov"  , "i32_mr_t_shr_mov"  , "i32_mr_t_mod_mov"  , "u32_r_mr_and_mov"  , "u32_r_mr_or_mov"   , "u32_r_mr_xor_mov"  , "u32_r_mr_shl_mov"  , 
    "u32_r_mr_shr_mov"  , "u32_r_mr_mod_mov"  , "u32_r_r_and_mov"   , "u32_r_r_or_mov"    , "u32_r_r_xor_mov"   , "u32_r_r_shl_mov"   , "u32_r_r_shr_mov"   , "u32_r_r_mod_mov"   , "u32_r_t_and_mov"   , "u32_r_t_or_mov"    , 
    "u32_r_t_xor_mov"   , "u32_r_t_shl_mov"   , "u32_r_t_shr_mov"   , "u32_r_t_mod_mov"   , "u32_mr_mr_and_mov" , "u32_mr_mr_or_mov"  , "u32_mr_mr_xor_mov" , "u32_mr_mr_shl_mov" , "u32_mr_mr_shr_mov" , "u32_mr_mr_mod_mov" , 
    "u32_mr_r_and_mov"  , "u32_mr_r_or_mov"   , "u32_mr_r_xor_mov"  , "u32_mr_r_shl_mov"  , "u32_mr_r_shr_mov"  , "u32_mr_r_mod_mov"  , "u32_mr_t_and_mov"  , "u32_mr_t_or_mov"   , "u32_mr_t_xor_mov"  , "u32_mr_t_shl_mov"  , 
    "u32_mr_t_shr_mov"  , "u32_mr_t_mod_mov"  , "i64_r_mr_and_mov"  , "i64_r_mr_or_mov"   , "i64_r_mr_xor_mov"  , "i64_r_mr_shl_mov"  , "i64_r_mr_shr_mov"  , "i64_r_mr_mod_mov"  , "i64_r_r_and_mov"   , "i64_r_r_or_mov"    , 
    "i64_r_r_xor_mov"   , "i64_r_r_shl_mov"   , "i64_r_r_shr_mov"   , "i64_r_r_mod_mov"   , "i64_r_t_and_mov"   , "i64_r_t_or_mov"    , "i64_r_t_xor_mov"   , "i64_r_t_shl_mov"   , "i64_r_t_shr_mov"   , "i64_r_t_mod_mov"   , 
    "i64_mr_mr_and_mov" , "i64_mr_mr_or_mov"  , "i64_mr_mr_xor_mov" , "i64_mr_mr_shl_mov" , "i64_mr_mr_shr_mov" , "i64_mr_mr_mod_mov" , "i64_mr_r_and_mov"  , "i64_mr_r_or_mov"   , "i64_mr_r_xor_mov"  , "i64_mr_r_shl_mov"  , 
    "i64_mr_r_shr_mov"  , "i64_mr_r_mod_mov"  , "i64_mr_t_and_mov"  , "i64_mr_t_or_mov"   , "i64_mr_t_xor_mov"  , "i64_mr_t_shl_mov"  , "i64_mr_t_shr_mov"  , "i64_mr_t_mod_mov"  , "u64_r_mr_and_mov"  , "u64_r_mr_or_mov"   , 
    "u64_r_mr_xor_mov"  , "u64_r_mr_shl_mov"  , "u64_r_mr_shr_mov"  , "u64_r_mr_mod_mov"  , "u64_r_r_and_mov"   , "u64_r_r_or_mov"    , "u64_r_r_xor_mov"   , "u64_r_r_shl_mov"   , "u64_r_r_shr_mov"   , "u64_r_r_mod_mov"   , 
    "u64_r_t_and_mov"   , "u64_r_t_or_mov"    , "u64_r_t_xor_mov"   , "u64_r_t_shl_mov"   , "u64_r_t_shr_mov"   , "u64_r_t_mod_mov"   , "u64_mr_mr_and_mov" , "u64_mr_mr_or_mov"  , "u64_mr_mr_xor_mov" , "u64_mr_mr_shl_mov" , 
    "u64_mr_mr_shr_mov" , "u64_mr_mr_mod_mov" , "u64_mr_r_and_mov"  , "u64_mr_r_or_mov"   , "u64_mr_r_xor_mov"  , "u64_mr_r_shl_mov"  , "u64_mr_r_shr_mov"  , "u64_mr_r_mod_mov"  , "u64_mr_t_and_mov"  , "u64_mr_t_or_mov"   , 
    "u64_mr_t_xor_mov"  , "u64_mr_t_shl_mov"  , "u64_mr_t_shr_mov"  , "u64_mr_t_mod_mov"  , 
    "c_add"             , "c_sub"             , "c_mul"             , "c_div"             , "b_add"             , "b_sub"             , 
    "b_mul"             , "b_div"             , "i16_add"           , "i16_sub"           , "i16_mul"           , "i16_div"           , "u16_add"           , "u16_sub"           , "u16_mul"           , "u16_div"           , 
    "i32_add"           , "i32_sub"           , "i32_mul"           , "i32_div"           , "u32_add"           , "u32_sub"           , "u32_mul"           , "u32_div"           , "i64_add"           , "i64_sub"           , 
    "i64_mul"           , "i64_div"           , "u64_add"           , "u64_sub"           , "u64_mul"           , "u64_div"           , "f32_add"           , "f32_sub"           , "f32_mul"           , "f32_div"           , 
    "f64_add"           , "f64_sub"           , "f64_mul"           , "f64_div"           , 
    "c_add"             , "c_or"              , "c_xor"             , "c_shl"             , "c_shr"             , "c_mod"             , 
    "b_add"             , "b_or"              , "b_xor"             , "b_shl"             , "b_shr"             , "b_mod"             , "i16_add"           , "i16_or"            , "i16_xor"           , "i16_shl"           , 
    "i16_shr"           , "i16_mod"           , "u16_add"           , "u16_or"            , "u16_xor"           , "u16_shl"           , "u16_shr"           , "u16_mod"           , "i32_add"           , "i32_or"            , 
    "i32_xor"           , "i32_shl"           , "i32_shr"           , "i32_mod"           , "u32_add"           , "u32_or"            , "u32_xor"           , "u32_shl"           , "u32_shr"           , "u32_mod"           , 
    "i64_add"           , "i64_or"            , "i64_xor"           , "i64_shl"           , "i64_shr"           , "i64_mod"           , "u64_add"           , "u64_or"            , "u64_xor"           , "u64_shl"           , 
    "u64_shr"           , "u64_mod"           , 
    "c_eq"              , "c_ne"              , "c_gt"              , "c_ge"              , "c_ls"              , "c_le"              , "b_eq"              , "b_ne"              , 
    "b_gt"              , "b_ge"              , "b_ls"              , "b_le"              , "i16_eq"            , "i16_ne"            , "i16_gt"            , "i16_ge"            , "i16_ls"            , "i16_le"            , 
    "u16_eq"            , "u16_ne"            , "u16_gt"            , "u16_ge"            , "u16_ls"            , "u16_le"            , "i32_eq"            , "i32_ne"            , "i32_gt"            , "i32_ge"            , 
    "i32_ls"            , "i32_le"            , "u32_eq"            , "u32_ne"            , "u32_gt"            , "u32_ge"            , "u32_ls"            , "u32_le"            , "i64_eq"            , "i64_ne"            , 
    "i64_gt"            , "i64_ge"            , "i64_ls"            , "i64_le"            , "u64_eq"            , "u64_ne"            , "u64_gt"            , "u64_ge"            , "u64_ls"            , "u64_le"            , 
    "f32_eq"            , "f32_ne"            , "f32_gt"            , "f32_ge"            , "f32_ls"            , "f32_le"            , "f64_eq"            , "f64_ne"            , "f64_gt"            , "f64_ge"            , 
    "c_c_r_r_cvt"       , "c_c_r_mr_cvt"      , "c_c_r_t_cvt"       , "c_c_mr_r_cvt"      , "c_c_mr_mr_cvt"     , "c_c_mr_t_cvt"      , "c_c_t_r_cvt"       , "c_c_t_mr_cvt"      , "c_c_t_t_cvt"       , "c_b_r_r_cvt"       , 
    "c_b_r_mr_cvt"      , "c_b_r_t_cvt"       , "c_b_mr_r_cvt"      , "c_b_mr_mr_cvt"     , "c_b_mr_t_cvt"      , "c_b_t_r_cvt"       , "c_b_t_mr_cvt"      , "c_b_t_t_cvt"       , "c_i16_r_r_cvt"     , "c_i16_r_mr_cvt"    , 
    "c_i16_r_t_cvt"     , "c_i16_mr_r_cvt"    , "c_i16_mr_mr_cvt"   , "c_i16_mr_t_cvt"    , "c_i16_t_r_cvt"     , "c_i16_t_mr_cvt"    , "c_i16_t_t_cvt"     , "c_u16_r_r_cvt"     , "c_u16_r_mr_cvt"    , "c_u16_r_t_cvt"     , 
    "c_u16_mr_r_cvt"    , "c_u16_mr_mr_cvt"   , "c_u16_mr_t_cvt"    , "c_u16_t_r_cvt"     , "c_u16_t_mr_cvt"    , "c_u16_t_t_cvt"     , "c_i32_r_r_cvt"     , "c_i32_r_mr_cvt"    , "c_i32_r_t_cvt"     , "c_i32_mr_r_cvt"    , 
    "c_i32_mr_mr_cvt"   , "c_i32_mr_t_cvt"    , "c_i32_t_r_cvt"     , "c_i32_t_mr_cvt"    , "c_i32_t_t_cvt"     , "c_u32_r_r_cvt"     , "c_u32_r_mr_cvt"    , "c_u32_r_t_cvt"     , "c_u32_mr_r_cvt"    , "c_u32_mr_mr_cvt"   , 
    "c_u32_mr_t_cvt"    , "c_u32_t_r_cvt"     , "c_u32_t_mr_cvt"    , "c_u32_t_t_cvt"     , "c_i64_r_r_cvt"     , "c_i64_r_mr_cvt"    , "c_i64_r_t_cvt"     , "c_i64_mr_r_cvt"    , "c_i64_mr_mr_cvt"   , "c_i64_mr_t_cvt"    , 
    "c_i64_t_r_cvt"     , "c_i64_t_mr_cvt"    , "c_i64_t_t_cvt"     , "c_u64_r_r_cvt"     , "c_u64_r_mr_cvt"    , "c_u64_r_t_cvt"     , "c_u64_mr_r_cvt"    , "c_u64_mr_mr_cvt"   , "c_u64_mr_t_cvt"    , "c_u64_t_r_cvt"     , 
    "c_u64_t_mr_cvt"    , "c_u64_t_t_cvt"     , "c_f32_r_r_cvt"     , "c_f32_r_mr_cvt"    , "c_f32_r_t_cvt"     , "c_f32_mr_r_cvt"    , "c_f32_mr_mr_cvt"   , "c_f32_mr_t_cvt"    , "c_f32_t_r_cvt"     , "c_f32_t_mr_cvt"    , 
    "c_f32_t_t_cvt"     , "c_f64_r_r_cvt"     , "c_f64_r_mr_cvt"    , "c_f64_r_t_cvt"     , "c_f64_mr_r_cvt"    , "c_f64_mr_mr_cvt"   , "c_f64_mr_t_cvt"    , "c_f64_t_r_cvt"     , "c_f64_t_mr_cvt"    , "c_f64_t_t_cvt"     , 
    "c_B_r_r_cvt"       , "c_B_r_mr_cvt"      , "c_B_r_t_cvt"       , "c_B_mr_r_cvt"      , "c_B_mr_mr_cvt"     , "c_B_mr_t_cvt"      , "c_B_t_r_cvt"       , "c_B_t_mr_cvt"      , "c_B_t_t_cvt"       , "b_c_r_r_cvt"       , 
    "b_c_r_mr_cvt"      , "b_c_r_t_cvt"       , "b_c_mr_r_cvt"      , "b_c_mr_mr_cvt"     , "b_c_mr_t_cvt"      , "b_c_t_r_cvt"       , "b_c_t_mr_cvt"      , "b_c_t_t_cvt"       , "b_b_r_r_cvt"       , "b_b_r_mr_cvt"      , 
    "b_b_r_t_cvt"       , "b_b_mr_r_cvt"      , "b_b_mr_mr_cvt"     , "b_b_mr_t_cvt"      , "b_b_t_r_cvt"       , "b_b_t_mr_cvt"      , "b_b_t_t_cvt"       , "b_i16_r_r_cvt"     , "b_i16_r_mr_cvt"    , "b_i16_r_t_cvt"     , 
    "b_i16_mr_r_cvt"    , "b_i16_mr_mr_cvt"   , "b_i16_mr_t_cvt"    , "b_i16_t_r_cvt"     , "b_i16_t_mr_cvt"    , "b_i16_t_t_cvt"     , "b_u16_r_r_cvt"     , "b_u16_r_mr_cvt"    , "b_u16_r_t_cvt"     , "b_u16_mr_r_cvt"    , 
    "b_u16_mr_mr_cvt"   , "b_u16_mr_t_cvt"    , "b_u16_t_r_cvt"     , "b_u16_t_mr_cvt"    , "b_u16_t_t_cvt"     , "b_i32_r_r_cvt"     , "b_i32_r_mr_cvt"    , "b_i32_r_t_cvt"     , "b_i32_mr_r_cvt"    , "b_i32_mr_mr_cvt"   , 
    "b_i32_mr_t_cvt"    , "b_i32_t_r_cvt"     , "b_i32_t_mr_cvt"    , "b_i32_t_t_cvt"     , "b_u32_r_r_cvt"     , "b_u32_r_mr_cvt"    , "b_u32_r_t_cvt"     , "b_u32_mr_r_cvt"    , "b_u32_mr_mr_cvt"   , "b_u32_mr_t_cvt"    , 
    "b_u32_t_r_cvt"     , "b_u32_t_mr_cvt"    , "b_u32_t_t_cvt"     , "b_i64_r_r_cvt"     , "b_i64_r_mr_cvt"    , "b_i64_r_t_cvt"     , "b_i64_mr_r_cvt"    , "b_i64_mr_mr_cvt"   , "b_i64_mr_t_cvt"    , "b_i64_t_r_cvt"     , 
    "b_i64_t_mr_cvt"    , "b_i64_t_t_cvt"     , "b_u64_r_r_cvt"     , "b_u64_r_mr_cvt"    , "b_u64_r_t_cvt"     , "b_u64_mr_r_cvt"    , "b_u64_mr_mr_cvt"   , "b_u64_mr_t_cvt"    , "b_u64_t_r_cvt"     , "b_u64_t_mr_cvt"    , 
    "b_u64_t_t_cvt"     , "b_f32_r_r_cvt"     , "b_f32_r_mr_cvt"    , "b_f32_r_t_cvt"     , "b_f32_mr_r_cvt"    , "b_f32_mr_mr_cvt"   , "b_f32_mr_t_cvt"    , "b_f32_t_r_cvt"     , "b_f32_t_mr_cvt"    , "b_f32_t_t_cvt"     , 
    "b_f64_r_r_cvt"     , "b_f64_r_mr_cvt"    , "b_f64_r_t_cvt"     , "b_f64_mr_r_cvt"    , "b_f64_mr_mr_cvt"   , "b_f64_mr_t_cvt"    , "b_f64_t_r_cvt"     , "b_f64_t_mr_cvt"    , "b_f64_t_t_cvt"     , "b_B_r_r_cvt"       , 
    "b_B_r_mr_cvt"      , "b_B_r_t_cvt"       , "b_B_mr_r_cvt"      , "b_B_mr_mr_cvt"     , "b_B_mr_t_cvt"      , "b_B_t_r_cvt"       , "b_B_t_mr_cvt"      , "b_B_t_t_cvt"       , "i16_c_r_r_cvt"     , "i16_c_r_mr_cvt"    , 
    "i16_c_r_t_cvt"     , "i16_c_mr_r_cvt"    , "i16_c_mr_mr_cvt"   , "i16_c_mr_t_cvt"    , "i16_c_t_r_cvt"     , "i16_c_t_mr_cvt"    , "i16_c_t_t_cvt"     , "i16_b_r_r_cvt"     , "i16_b_r_mr_cvt"    , "i16_b_r_t_cvt"     , 
    "i16_b_mr_r_cvt"    , "i16_b_mr_mr_cvt"   , "i16_b_mr_t_cvt"    , "i16_b_t_r_cvt"     , "i16_b_t_mr_cvt"    , "i16_b_t_t_cvt"     , "i16_i16_r_r_cvt"   , "i16_i16_r_mr_cvt"  , "i16_i16_r_t_cvt"   , "i16_i16_mr_r_cvt"  , 
    "i16_i16_mr_mr_cvt" , "i16_i16_mr_t_cvt"  , "i16_i16_t_r_cvt"   , "i16_i16_t_mr_cvt"  , "i16_i16_t_t_cvt"   , "i16_u16_r_r_cvt"   , "i16_u16_r_mr_cvt"  , "i16_u16_r_t_cvt"   , "i16_u16_mr_r_cvt"  , "i16_u16_mr_mr_cvt" , 
    "i16_u16_mr_t_cvt"  , "i16_u16_t_r_cvt"   , "i16_u16_t_mr_cvt"  , "i16_u16_t_t_cvt"   , "i16_i32_r_r_cvt"   , "i16_i32_r_mr_cvt"  , "i16_i32_r_t_cvt"   , "i16_i32_mr_r_cvt"  , "i16_i32_mr_mr_cvt" , "i16_i32_mr_t_cvt"  , 
    "i16_i32_t_r_cvt"   , "i16_i32_t_mr_cvt"  , "i16_i32_t_t_cvt"   , "i16_u32_r_r_cvt"   , "i16_u32_r_mr_cvt"  , "i16_u32_r_t_cvt"   , "i16_u32_mr_r_cvt"  , "i16_u32_mr_mr_cvt" , "i16_u32_mr_t_cvt"  , "i16_u32_t_r_cvt"   , 
    "i16_u32_t_mr_cvt"  , "i16_u32_t_t_cvt"   , "i16_i64_r_r_cvt"   , "i16_i64_r_mr_cvt"  , "i16_i64_r_t_cvt"   , "i16_i64_mr_r_cvt"  , "i16_i64_mr_mr_cvt" , "i16_i64_mr_t_cvt"  , "i16_i64_t_r_cvt"   , "i16_i64_t_mr_cvt"  , 
    "i16_i64_t_t_cvt"   , "i16_u64_r_r_cvt"   , "i16_u64_r_mr_cvt"  , "i16_u64_r_t_cvt"   , "i16_u64_mr_r_cvt"  , "i16_u64_mr_mr_cvt" , "i16_u64_mr_t_cvt"  , "i16_u64_t_r_cvt"   , "i16_u64_t_mr_cvt"  , "i16_u64_t_t_cvt"   , 
    "i16_f32_r_r_cvt"   , "i16_f32_r_mr_cvt"  , "i16_f32_r_t_cvt"   , "i16_f32_mr_r_cvt"  , "i16_f32_mr_mr_cvt" , "i16_f32_mr_t_cvt"  , "i16_f32_t_r_cvt"   , "i16_f32_t_mr_cvt"  , "i16_f32_t_t_cvt"   , "i16_f64_r_r_cvt"   , 
    "i16_f64_r_mr_cvt"  , "i16_f64_r_t_cvt"   , "i16_f64_mr_r_cvt"  , "i16_f64_mr_mr_cvt" , "i16_f64_mr_t_cvt"  , "i16_f64_t_r_cvt"   , "i16_f64_t_mr_cvt"  , "i16_f64_t_t_cvt"   , "i16_B_r_r_cvt"     , "i16_B_r_mr_cvt"    , 
    "i16_B_r_t_cvt"     , "i16_B_mr_r_cvt"    , "i16_B_mr_mr_cvt"   , "i16_B_mr_t_cvt"    , "i16_B_t_r_cvt"     , "i16_B_t_mr_cvt"    , "i16_B_t_t_cvt"     , "u16_c_r_r_cvt"     , "u16_c_r_mr_cvt"    , "u16_c_r_t_cvt"     , 
    "u16_c_mr_r_cvt"    , "u16_c_mr_mr_cvt"   , "u16_c_mr_t_cvt"    , "u16_c_t_r_cvt"     , "u16_c_t_mr_cvt"    , "u16_c_t_t_cvt"     , "u16_b_r_r_cvt"     , "u16_b_r_mr_cvt"    , "u16_b_r_t_cvt"     , "u16_b_mr_r_cvt"    , 
    "u16_b_mr_mr_cvt"   , "u16_b_mr_t_cvt"    , "u16_b_t_r_cvt"     , "u16_b_t_mr_cvt"    , "u16_b_t_t_cvt"     , "u16_i16_r_r_cvt"   , "u16_i16_r_mr_cvt"  , "u16_i16_r_t_cvt"   , "u16_i16_mr_r_cvt"  , "u16_i16_mr_mr_cvt" , 
    "u16_i16_mr_t_cvt"  , "u16_i16_t_r_cvt"   , "u16_i16_t_mr_cvt"  , "u16_i16_t_t_cvt"   , "u16_u16_r_r_cvt"   , "u16_u16_r_mr_cvt"  , "u16_u16_r_t_cvt"   , "u16_u16_mr_r_cvt"  , "u16_u16_mr_mr_cvt" , "u16_u16_mr_t_cvt"  , 
    "u16_u16_t_r_cvt"   , "u16_u16_t_mr_cvt"  , "u16_u16_t_t_cvt"   , "u16_i32_r_r_cvt"   , "u16_i32_r_mr_cvt"  , "u16_i32_r_t_cvt"   , "u16_i32_mr_r_cvt"  , "u16_i32_mr_mr_cvt" , "u16_i32_mr_t_cvt"  , "u16_i32_t_r_cvt"   , 
    "u16_i32_t_mr_cvt"  , "u16_i32_t_t_cvt"   , "u16_u32_r_r_cvt"   , "u16_u32_r_mr_cvt"  , "u16_u32_r_t_cvt"   , "u16_u32_mr_r_cvt"  , "u16_u32_mr_mr_cvt" , "u16_u32_mr_t_cvt"  , "u16_u32_t_r_cvt"   , "u16_u32_t_mr_cvt"  , 
    "u16_u32_t_t_cvt"   , "u16_i64_r_r_cvt"   , "u16_i64_r_mr_cvt"  , "u16_i64_r_t_cvt"   , "u16_i64_mr_r_cvt"  , "u16_i64_mr_mr_cvt" , "u16_i64_mr_t_cvt"  , "u16_i64_t_r_cvt"   , "u16_i64_t_mr_cvt"  , "u16_i64_t_t_cvt"   , 
    "u16_u64_r_r_cvt"   , "u16_u64_r_mr_cvt"  , "u16_u64_r_t_cvt"   , "u16_u64_mr_r_cvt"  , "u16_u64_mr_mr_cvt" , "u16_u64_mr_t_cvt"  , "u16_u64_t_r_cvt"   , "u16_u64_t_mr_cvt"  , "u16_u64_t_t_cvt"   , "u16_f32_r_r_cvt"   , 
    "u16_f32_r_mr_cvt"  , "u16_f32_r_t_cvt"   , "u16_f32_mr_r_cvt"  , "u16_f32_mr_mr_cvt" , "u16_f32_mr_t_cvt"  , "u16_f32_t_r_cvt"   , "u16_f32_t_mr_cvt"  , "u16_f32_t_t_cvt"   , "u16_f64_r_r_cvt"   , "u16_f64_r_mr_cvt"  , 
    "u16_f64_r_t_cvt"   , "u16_f64_mr_r_cvt"  , "u16_f64_mr_mr_cvt" , "u16_f64_mr_t_cvt"  , "u16_f64_t_r_cvt"   , "u16_f64_t_mr_cvt"  , "u16_f64_t_t_cvt"   , "u16_B_r_r_cvt"     , "u16_B_r_mr_cvt"    , "u16_B_r_t_cvt"     , 
    "u16_B_mr_r_cvt"    , "u16_B_mr_mr_cvt"   , "u16_B_mr_t_cvt"    , "u16_B_t_r_cvt"     , "u16_B_t_mr_cvt"    , "u16_B_t_t_cvt"     , "i32_c_r_r_cvt"     , "i32_c_r_mr_cvt"    , "i32_c_r_t_cvt"     , "i32_c_mr_r_cvt"    , 
    "i32_c_mr_mr_cvt"   , "i32_c_mr_t_cvt"    , "i32_c_t_r_cvt"     , "i32_c_t_mr_cvt"    , "i32_c_t_t_cvt"     , "i32_b_r_r_cvt"     , "i32_b_r_mr_cvt"    , "i32_b_r_t_cvt"     , "i32_b_mr_r_cvt"    , "i32_b_mr_mr_cvt"   , 
    "i32_b_mr_t_cvt"    , "i32_b_t_r_cvt"     , "i32_b_t_mr_cvt"    , "i32_b_t_t_cvt"     , "i32_i16_r_r_cvt"   , "i32_i16_r_mr_cvt"  , "i32_i16_r_t_cvt"   , "i32_i16_mr_r_cvt"  , "i32_i16_mr_mr_cvt" , "i32_i16_mr_t_cvt"  , 
    "i32_i16_t_r_cvt"   , "i32_i16_t_mr_cvt"  , "i32_i16_t_t_cvt"   , "i32_u16_r_r_cvt"   , "i32_u16_r_mr_cvt"  , "i32_u16_r_t_cvt"   , "i32_u16_mr_r_cvt"  , "i32_u16_mr_mr_cvt" , "i32_u16_mr_t_cvt"  , "i32_u16_t_r_cvt"   , 
    "i32_u16_t_mr_cvt"  , "i32_u16_t_t_cvt"   , "i32_i32_r_r_cvt"   , "i32_i32_r_mr_cvt"  , "i32_i32_r_t_cvt"   , "i32_i32_mr_r_cvt"  , "i32_i32_mr_mr_cvt" , "i32_i32_mr_t_cvt"  , "i32_i32_t_r_cvt"   , "i32_i32_t_mr_cvt"  , 
    "i32_i32_t_t_cvt"   , "i32_u32_r_r_cvt"   , "i32_u32_r_mr_cvt"  , "i32_u32_r_t_cvt"   , "i32_u32_mr_r_cvt"  , "i32_u32_mr_mr_cvt" , "i32_u32_mr_t_cvt"  , "i32_u32_t_r_cvt"   , "i32_u32_t_mr_cvt"  , "i32_u32_t_t_cvt"   , 
    "i32_i64_r_r_cvt"   , "i32_i64_r_mr_cvt"  , "i32_i64_r_t_cvt"   , "i32_i64_mr_r_cvt"  , "i32_i64_mr_mr_cvt" , "i32_i64_mr_t_cvt"  , "i32_i64_t_r_cvt"   , "i32_i64_t_mr_cvt"  , "i32_i64_t_t_cvt"   , "i32_u64_r_r_cvt"   , 
    "i32_u64_r_mr_cvt"  , "i32_u64_r_t_cvt"   , "i32_u64_mr_r_cvt"  , "i32_u64_mr_mr_cvt" , "i32_u64_mr_t_cvt"  , "i32_u64_t_r_cvt"   , "i32_u64_t_mr_cvt"  , "i32_u64_t_t_cvt"   , "i32_f32_r_r_cvt"   , "i32_f32_r_mr_cvt"  , 
    "i32_f32_r_t_cvt"   , "i32_f32_mr_r_cvt"  , "i32_f32_mr_mr_cvt" , "i32_f32_mr_t_cvt"  , "i32_f32_t_r_cvt"   , "i32_f32_t_mr_cvt"  , "i32_f32_t_t_cvt"   , "i32_f64_r_r_cvt"   , "i32_f64_r_mr_cvt"  , "i32_f64_r_t_cvt"   , 
    "i32_f64_mr_r_cvt"  , "i32_f64_mr_mr_cvt" , "i32_f64_mr_t_cvt"  , "i32_f64_t_r_cvt"   , "i32_f64_t_mr_cvt"  , "i32_f64_t_t_cvt"   , "i32_B_r_r_cvt"     , "i32_B_r_mr_cvt"    , "i32_B_r_t_cvt"     , "i32_B_mr_r_cvt"    , 
    "i32_B_mr_mr_cvt"   , "i32_B_mr_t_cvt"    , "i32_B_t_r_cvt"     , "i32_B_t_mr_cvt"    , "i32_B_t_t_cvt"     , "u32_c_r_r_cvt"     , "u32_c_r_mr_cvt"    , "u32_c_r_t_cvt"     , "u32_c_mr_r_cvt"    , "u32_c_mr_mr_cvt"   , 
    "u32_c_mr_t_cvt"    , "u32_c_t_r_cvt"     , "u32_c_t_mr_cvt"    , "u32_c_t_t_cvt"     , "u32_b_r_r_cvt"     , "u32_b_r_mr_cvt"    , "u32_b_r_t_cvt"     , "u32_b_mr_r_cvt"    , "u32_b_mr_mr_cvt"   , "u32_b_mr_t_cvt"    , 
    "u32_b_t_r_cvt"     , "u32_b_t_mr_cvt"    , "u32_b_t_t_cvt"     , "u32_i16_r_r_cvt"   , "u32_i16_r_mr_cvt"  , "u32_i16_r_t_cvt"   , "u32_i16_mr_r_cvt"  , "u32_i16_mr_mr_cvt" , "u32_i16_mr_t_cvt"  , "u32_i16_t_r_cvt"   , 
    "u32_i16_t_mr_cvt"  , "u32_i16_t_t_cvt"   , "u32_u16_r_r_cvt"   , "u32_u16_r_mr_cvt"  , "u32_u16_r_t_cvt"   , "u32_u16_mr_r_cvt"  , "u32_u16_mr_mr_cvt" , "u32_u16_mr_t_cvt"  , "u32_u16_t_r_cvt"   , "u32_u16_t_mr_cvt"  , 
    "u32_u16_t_t_cvt"   , "u32_i32_r_r_cvt"   , "u32_i32_r_mr_cvt"  , "u32_i32_r_t_cvt"   , "u32_i32_mr_r_cvt"  , "u32_i32_mr_mr_cvt" , "u32_i32_mr_t_cvt"  , "u32_i32_t_r_cvt"   , "u32_i32_t_mr_cvt"  , "u32_i32_t_t_cvt"   , 
    "u32_u32_r_r_cvt"   , "u32_u32_r_mr_cvt"  , "u32_u32_r_t_cvt"   , "u32_u32_mr_r_cvt"  , "u32_u32_mr_mr_cvt" , "u32_u32_mr_t_cvt"  , "u32_u32_t_r_cvt"   , "u32_u32_t_mr_cvt"  , "u32_u32_t_t_cvt"   , "u32_i64_r_r_cvt"   , 
    "u32_i64_r_mr_cvt"  , "u32_i64_r_t_cvt"   , "u32_i64_mr_r_cvt"  , "u32_i64_mr_mr_cvt" , "u32_i64_mr_t_cvt"  , "u32_i64_t_r_cvt"   , "u32_i64_t_mr_cvt"  , "u32_i64_t_t_cvt"   , "u32_u64_r_r_cvt"   , "u32_u64_r_mr_cvt"  , 
    "u32_u64_r_t_cvt"   , "u32_u64_mr_r_cvt"  , "u32_u64_mr_mr_cvt" , "u32_u64_mr_t_cvt"  , "u32_u64_t_r_cvt"   , "u32_u64_t_mr_cvt"  , "u32_u64_t_t_cvt"   , "u32_f32_r_r_cvt"   , "u32_f32_r_mr_cvt"  , "u32_f32_r_t_cvt"   , 
    "u32_f32_mr_r_cvt"  , "u32_f32_mr_mr_cvt" , "u32_f32_mr_t_cvt"  , "u32_f32_t_r_cvt"   , "u32_f32_t_mr_cvt"  , "u32_f32_t_t_cvt"   , "u32_f64_r_r_cvt"   , "u32_f64_r_mr_cvt"  , "u32_f64_r_t_cvt"   , "u32_f64_mr_r_cvt"  , 
    "u32_f64_mr_mr_cvt" , "u32_f64_mr_t_cvt"  , "u32_f64_t_r_cvt"   , "u32_f64_t_mr_cvt"  , "u32_f64_t_t_cvt"   , "u32_B_r_r_cvt"     , "u32_B_r_mr_cvt"    , "u32_B_r_t_cvt"     , "u32_B_mr_r_cvt"    , "u32_B_mr_mr_cvt"   , 
    "u32_B_mr_t_cvt"    , "u32_B_t_r_cvt"     , "u32_B_t_mr_cvt"    , "u32_B_t_t_cvt"     , "i64_c_r_r_cvt"     , "i64_c_r_mr_cvt"    , "i64_c_r_t_cvt"     , "i64_c_mr_r_cvt"    , "i64_c_mr_mr_cvt"   , "i64_c_mr_t_cvt"    , 
    "i64_c_t_r_cvt"     , "i64_c_t_mr_cvt"    , "i64_c_t_t_cvt"     , "i64_b_r_r_cvt"     , "i64_b_r_mr_cvt"    , "i64_b_r_t_cvt"     , "i64_b_mr_r_cvt"    , "i64_b_mr_mr_cvt"   , "i64_b_mr_t_cvt"    , "i64_b_t_r_cvt"     , 
    "i64_b_t_mr_cvt"    , "i64_b_t_t_cvt"     , "i64_i16_r_r_cvt"   , "i64_i16_r_mr_cvt"  , "i64_i16_r_t_cvt"   , "i64_i16_mr_r_cvt"  , "i64_i16_mr_mr_cvt" , "i64_i16_mr_t_cvt"  , "i64_i16_t_r_cvt"   , "i64_i16_t_mr_cvt"  , 
    "i64_i16_t_t_cvt"   , "i64_u16_r_r_cvt"   , "i64_u16_r_mr_cvt"  , "i64_u16_r_t_cvt"   , "i64_u16_mr_r_cvt"  , "i64_u16_mr_mr_cvt" , "i64_u16_mr_t_cvt"  , "i64_u16_t_r_cvt"   , "i64_u16_t_mr_cvt"  , "i64_u16_t_t_cvt"   , 
    "i64_i32_r_r_cvt"   , "i64_i32_r_mr_cvt"  , "i64_i32_r_t_cvt"   , "i64_i32_mr_r_cvt"  , "i64_i32_mr_mr_cvt" , "i64_i32_mr_t_cvt"  , "i64_i32_t_r_cvt"   , "i64_i32_t_mr_cvt"  , "i64_i32_t_t_cvt"   , "i64_u32_r_r_cvt"   , 
    "i64_u32_r_mr_cvt"  , "i64_u32_r_t_cvt"   , "i64_u32_mr_r_cvt"  , "i64_u32_mr_mr_cvt" , "i64_u32_mr_t_cvt"  , "i64_u32_t_r_cvt"   , "i64_u32_t_mr_cvt"  , "i64_u32_t_t_cvt"   , "i64_i64_r_r_cvt"   , "i64_i64_r_mr_cvt"  , 
    "i64_i64_r_t_cvt"   , "i64_i64_mr_r_cvt"  , "i64_i64_mr_mr_cvt" , "i64_i64_mr_t_cvt"  , "i64_i64_t_r_cvt"   , "i64_i64_t_mr_cvt"  , "i64_i64_t_t_cvt"   , "i64_u64_r_r_cvt"   , "i64_u64_r_mr_cvt"  , "i64_u64_r_t_cvt"   , 
    "i64_u64_mr_r_cvt"  , "i64_u64_mr_mr_cvt" , "i64_u64_mr_t_cvt"  , "i64_u64_t_r_cvt"   , "i64_u64_t_mr_cvt"  , "i64_u64_t_t_cvt"   , "i64_f32_r_r_cvt"   , "i64_f32_r_mr_cvt"  , "i64_f32_r_t_cvt"   , "i64_f32_mr_r_cvt"  , 
    "i64_f32_mr_mr_cvt" , "i64_f32_mr_t_cvt"  , "i64_f32_t_r_cvt"   , "i64_f32_t_mr_cvt"  , "i64_f32_t_t_cvt"   , "i64_f64_r_r_cvt"   , "i64_f64_r_mr_cvt"  , "i64_f64_r_t_cvt"   , "i64_f64_mr_r_cvt"  , "i64_f64_mr_mr_cvt" , 
    "i64_f64_mr_t_cvt"  , "i64_f64_t_r_cvt"   , "i64_f64_t_mr_cvt"  , "i64_f64_t_t_cvt"   , "i64_B_r_r_cvt"     , "i64_B_r_mr_cvt"    , "i64_B_r_t_cvt"     , "i64_B_mr_r_cvt"    , "i64_B_mr_mr_cvt"   , "i64_B_mr_t_cvt"    , 
    "i64_B_t_r_cvt"     , "i64_B_t_mr_cvt"    , "i64_B_t_t_cvt"     , "u64_c_r_r_cvt"     , "u64_c_r_mr_cvt"    , "u64_c_r_t_cvt"     , "u64_c_mr_r_cvt"    , "u64_c_mr_mr_cvt"   , "u64_c_mr_t_cvt"    , "u64_c_t_r_cvt"     , 
    "u64_c_t_mr_cvt"    , "u64_c_t_t_cvt"     , "u64_b_r_r_cvt"     , "u64_b_r_mr_cvt"    , "u64_b_r_t_cvt"     , "u64_b_mr_r_cvt"    , "u64_b_mr_mr_cvt"   , "u64_b_mr_t_cvt"    , "u64_b_t_r_cvt"     , "u64_b_t_mr_cvt"    , 
    "u64_b_t_t_cvt"     , "u64_i16_r_r_cvt"   , "u64_i16_r_mr_cvt"  , "u64_i16_r_t_cvt"   , "u64_i16_mr_r_cvt"  , "u64_i16_mr_mr_cvt" , "u64_i16_mr_t_cvt"  , "u64_i16_t_r_cvt"   , "u64_i16_t_mr_cvt"  , "u64_i16_t_t_cvt"   , 
    "u64_u16_r_r_cvt"   , "u64_u16_r_mr_cvt"  , "u64_u16_r_t_cvt"   , "u64_u16_mr_r_cvt"  , "u64_u16_mr_mr_cvt" , "u64_u16_mr_t_cvt"  , "u64_u16_t_r_cvt"   , "u64_u16_t_mr_cvt"  , "u64_u16_t_t_cvt"   , "u64_i32_r_r_cvt"   , 
    "u64_i32_r_mr_cvt"  , "u64_i32_r_t_cvt"   , "u64_i32_mr_r_cvt"  , "u64_i32_mr_mr_cvt" , "u64_i32_mr_t_cvt"  , "u64_i32_t_r_cvt"   , "u64_i32_t_mr_cvt"  , "u64_i32_t_t_cvt"   , "u64_u32_r_r_cvt"   , "u64_u32_r_mr_cvt"  , 
    "u64_u32_r_t_cvt"   , "u64_u32_mr_r_cvt"  , "u64_u32_mr_mr_cvt" , "u64_u32_mr_t_cvt"  , "u64_u32_t_r_cvt"   , "u64_u32_t_mr_cvt"  , "u64_u32_t_t_cvt"   , "u64_i64_r_r_cvt"   , "u64_i64_r_mr_cvt"  , "u64_i64_r_t_cvt"   , 
    "u64_i64_mr_r_cvt"  , "u64_i64_mr_mr_cvt" , "u64_i64_mr_t_cvt"  , "u64_i64_t_r_cvt"   , "u64_i64_t_mr_cvt"  , "u64_i64_t_t_cvt"   , "u64_u64_r_r_cvt"   , "u64_u64_r_mr_cvt"  , "u64_u64_r_t_cvt"   , "u64_u64_mr_r_cvt"  , 
    "u64_u64_mr_mr_cvt" , "u64_u64_mr_t_cvt"  , "u64_u64_t_r_cvt"   , "u64_u64_t_mr_cvt"  , "u64_u64_t_t_cvt"   , "u64_f32_r_r_cvt"   , "u64_f32_r_mr_cvt"  , "u64_f32_r_t_cvt"   , "u64_f32_mr_r_cvt"  , "u64_f32_mr_mr_cvt" , 
    "u64_f32_mr_t_cvt"  , "u64_f32_t_r_cvt"   , "u64_f32_t_mr_cvt"  , "u64_f32_t_t_cvt"   , "u64_f64_r_r_cvt"   , "u64_f64_r_mr_cvt"  , "u64_f64_r_t_cvt"   , "u64_f64_mr_r_cvt"  , "u64_f64_mr_mr_cvt" , "u64_f64_mr_t_cvt"  , 
    "u64_f64_t_r_cvt"   , "u64_f64_t_mr_cvt"  , "u64_f64_t_t_cvt"   , "u64_B_r_r_cvt"     , "u64_B_r_mr_cvt"    , "u64_B_r_t_cvt"     , "u64_B_mr_r_cvt"    , "u64_B_mr_mr_cvt"   , "u64_B_mr_t_cvt"    , "u64_B_t_r_cvt"     , 
    "u64_B_t_mr_cvt"    , "u64_B_t_t_cvt"     , "f32_c_r_r_cvt"     , "f32_c_r_mr_cvt"    , "f32_c_r_t_cvt"     , "f32_c_mr_r_cvt"    , "f32_c_mr_mr_cvt"   , "f32_c_mr_t_cvt"    , "f32_c_t_r_cvt"     , "f32_c_t_mr_cvt"    , 
    "f32_c_t_t_cvt"     , "f32_b_r_r_cvt"     , "f32_b_r_mr_cvt"    , "f32_b_r_t_cvt"     , "f32_b_mr_r_cvt"    , "f32_b_mr_mr_cvt"   , "f32_b_mr_t_cvt"    , "f32_b_t_r_cvt"     , "f32_b_t_mr_cvt"    , "f32_b_t_t_cvt"     , 
    "f32_i16_r_r_cvt"   , "f32_i16_r_mr_cvt"  , "f32_i16_r_t_cvt"   , "f32_i16_mr_r_cvt"  , "f32_i16_mr_mr_cvt" , "f32_i16_mr_t_cvt"  , "f32_i16_t_r_cvt"   , "f32_i16_t_mr_cvt"  , "f32_i16_t_t_cvt"   , "f32_u16_r_r_cvt"   , 
    "f32_u16_r_mr_cvt"  , "f32_u16_r_t_cvt"   , "f32_u16_mr_r_cvt"  , "f32_u16_mr_mr_cvt" , "f32_u16_mr_t_cvt"  , "f32_u16_t_r_cvt"   , "f32_u16_t_mr_cvt"  , "f32_u16_t_t_cvt"   , "f32_i32_r_r_cvt"   , "f32_i32_r_mr_cvt"  , 
    "f32_i32_r_t_cvt"   , "f32_i32_mr_r_cvt"  , "f32_i32_mr_mr_cvt" , "f32_i32_mr_t_cvt"  , "f32_i32_t_r_cvt"   , "f32_i32_t_mr_cvt"  , "f32_i32_t_t_cvt"   , "f32_u32_r_r_cvt"   , "f32_u32_r_mr_cvt"  , "f32_u32_r_t_cvt"   , 
    "f32_u32_mr_r_cvt"  , "f32_u32_mr_mr_cvt" , "f32_u32_mr_t_cvt"  , "f32_u32_t_r_cvt"   , "f32_u32_t_mr_cvt"  , "f32_u32_t_t_cvt"   , "f32_i64_r_r_cvt"   , "f32_i64_r_mr_cvt"  , "f32_i64_r_t_cvt"   , "f32_i64_mr_r_cvt"  , 
    "f32_i64_mr_mr_cvt" , "f32_i64_mr_t_cvt"  , "f32_i64_t_r_cvt"   , "f32_i64_t_mr_cvt"  , "f32_i64_t_t_cvt"   , "f32_u64_r_r_cvt"   , "f32_u64_r_mr_cvt"  , "f32_u64_r_t_cvt"   , "f32_u64_mr_r_cvt"  , "f32_u64_mr_mr_cvt" , 
    "f32_u64_mr_t_cvt"  , "f32_u64_t_r_cvt"   , "f32_u64_t_mr_cvt"  , "f32_u64_t_t_cvt"   , "f32_f32_r_r_cvt"   , "f32_f32_r_mr_cvt"  , "f32_f32_r_t_cvt"   , "f32_f32_mr_r_cvt"  , "f32_f32_mr_mr_cvt" , "f32_f32_mr_t_cvt"  , 
    "f32_f32_t_r_cvt"   , "f32_f32_t_mr_cvt"  , "f32_f32_t_t_cvt"   , "f32_f64_r_r_cvt"   , "f32_f64_r_mr_cvt"  , "f32_f64_r_t_cvt"   , "f32_f64_mr_r_cvt"  , "f32_f64_mr_mr_cvt" , "f32_f64_mr_t_cvt"  , "f32_f64_t_r_cvt"   , 
    "f32_f64_t_mr_cvt"  , "f32_f64_t_t_cvt"   , "f32_B_r_r_cvt"     , "f32_B_r_mr_cvt"    , "f32_B_r_t_cvt"     , "f32_B_mr_r_cvt"    , "f32_B_mr_mr_cvt"   , "f32_B_mr_t_cvt"    , "f32_B_t_r_cvt"     , "f32_B_t_mr_cvt"    , 
    "f32_B_t_t_cvt"     , "f64_c_r_r_cvt"     , "f64_c_r_mr_cvt"    , "f64_c_r_t_cvt"     , "f64_c_mr_r_cvt"    , "f64_c_mr_mr_cvt"   , "f64_c_mr_t_cvt"    , "f64_c_t_r_cvt"     , "f64_c_t_mr_cvt"    , "f64_c_t_t_cvt"     , 
    "f64_b_r_r_cvt"     , "f64_b_r_mr_cvt"    , "f64_b_r_t_cvt"     , "f64_b_mr_r_cvt"    , "f64_b_mr_mr_cvt"   , "f64_b_mr_t_cvt"    , "f64_b_t_r_cvt"     , "f64_b_t_mr_cvt"    , "f64_b_t_t_cvt"     , "f64_i16_r_r_cvt"   , 
    "f64_i16_r_mr_cvt"  , "f64_i16_r_t_cvt"   , "f64_i16_mr_r_cvt"  , "f64_i16_mr_mr_cvt" , "f64_i16_mr_t_cvt"  , "f64_i16_t_r_cvt"   , "f64_i16_t_mr_cvt"  , "f64_i16_t_t_cvt"   , "f64_u16_r_r_cvt"   , "f64_u16_r_mr_cvt"  , 
    "f64_u16_r_t_cvt"   , "f64_u16_mr_r_cvt"  , "f64_u16_mr_mr_cvt" , "f64_u16_mr_t_cvt"  , "f64_u16_t_r_cvt"   , "f64_u16_t_mr_cvt"  , "f64_u16_t_t_cvt"   , "f64_i32_r_r_cvt"   , "f64_i32_r_mr_cvt"  , "f64_i32_r_t_cvt"   , 
    "f64_i32_mr_r_cvt"  , "f64_i32_mr_mr_cvt" , "f64_i32_mr_t_cvt"  , "f64_i32_t_r_cvt"   , "f64_i32_t_mr_cvt"  , "f64_i32_t_t_cvt"   , "f64_u32_r_r_cvt"   , "f64_u32_r_mr_cvt"  , "f64_u32_r_t_cvt"   , "f64_u32_mr_r_cvt"  , 
    "f64_u32_mr_mr_cvt" , "f64_u32_mr_t_cvt"  , "f64_u32_t_r_cvt"   , "f64_u32_t_mr_cvt"  , "f64_u32_t_t_cvt"   , "f64_i64_r_r_cvt"   , "f64_i64_r_mr_cvt"  , "f64_i64_r_t_cvt"   , "f64_i64_mr_r_cvt"  , "f64_i64_mr_mr_cvt" , 
    "f64_i64_mr_t_cvt"  , "f64_i64_t_r_cvt"   , "f64_i64_t_mr_cvt"  , "f64_i64_t_t_cvt"   , "f64_u64_r_r_cvt"   , "f64_u64_r_mr_cvt"  , "f64_u64_r_t_cvt"   , "f64_u64_mr_r_cvt"  , "f64_u64_mr_mr_cvt" , "f64_u64_mr_t_cvt"  , 
    "f64_u64_t_r_cvt"   , "f64_u64_t_mr_cvt"  , "f64_u64_t_t_cvt"   , "f64_f32_r_r_cvt"   , "f64_f32_r_mr_cvt"  , "f64_f32_r_t_cvt"   , "f64_f32_mr_r_cvt"  , "f64_f32_mr_mr_cvt" , "f64_f32_mr_t_cvt"  , "f64_f32_t_r_cvt"   , 
    "f64_f32_t_mr_cvt"  , "f64_f32_t_t_cvt"   , "f64_f64_r_r_cvt"   , "f64_f64_r_mr_cvt"  , "f64_f64_r_t_cvt"   , "f64_f64_mr_r_cvt"  , "f64_f64_mr_mr_cvt" , "f64_f64_mr_t_cvt"  , "f64_f64_t_r_cvt"   , "f64_f64_t_mr_cvt"  , 
    "f64_f64_t_t_cvt"   , "f64_B_r_r_cvt"     , "f64_B_r_mr_cvt"    , "f64_B_r_t_cvt"     , "f64_B_mr_r_cvt"    , "f64_B_mr_mr_cvt"   , "f64_B_mr_t_cvt"    , "f64_B_t_r_cvt"     , "f64_B_t_mr_cvt"    , "f64_B_t_t_cvt"     , 
    "B_c_r_r_cvt"       , "B_c_r_mr_cvt"      , "B_c_r_t_cvt"       , "B_c_mr_r_cvt"      , "B_c_mr_mr_cvt"     , "B_c_mr_t_cvt"      , "B_c_t_r_cvt"       , "B_c_t_mr_cvt"      , "B_c_t_t_cvt"       , "B_b_r_r_cvt"       , 
    "B_b_r_mr_cvt"      , "B_b_r_t_cvt"       , "B_b_mr_r_cvt"      , "B_b_mr_mr_cvt"     , "B_b_mr_t_cvt"      , "B_b_t_r_cvt"       , "B_b_t_mr_cvt"      , "B_b_t_t_cvt"       , "B_i16_r_r_cvt"     , "B_i16_r_mr_cvt"    , 
    "B_i16_r_t_cvt"     , "B_i16_mr_r_cvt"    , "B_i16_mr_mr_cvt"   , "B_i16_mr_t_cvt"    , "B_i16_t_r_cvt"     , "B_i16_t_mr_cvt"    , "B_i16_t_t_cvt"     , "B_u16_r_r_cvt"     , "B_u16_r_mr_cvt"    , "B_u16_r_t_cvt"     , 
    "B_u16_mr_r_cvt"    , "B_u16_mr_mr_cvt"   , "B_u16_mr_t_cvt"    , "B_u16_t_r_cvt"     , "B_u16_t_mr_cvt"    , "B_u16_t_t_cvt"     , "B_i32_r_r_cvt"     , "B_i32_r_mr_cvt"    , "B_i32_r_t_cvt"     , "B_i32_mr_r_cvt"    , 
    "B_i32_mr_mr_cvt"   , "B_i32_mr_t_cvt"    , "B_i32_t_r_cvt"     , "B_i32_t_mr_cvt"    , "B_i32_t_t_cvt"     , "B_u32_r_r_cvt"     , "B_u32_r_mr_cvt"    , "B_u32_r_t_cvt"     , "B_u32_mr_r_cvt"    , "B_u32_mr_mr_cvt"   , 
    "B_u32_mr_t_cvt"    , "B_u32_t_r_cvt"     , "B_u32_t_mr_cvt"    , "B_u32_t_t_cvt"     , "B_i64_r_r_cvt"     , "B_i64_r_mr_cvt"    , "B_i64_r_t_cvt"     , "B_i64_mr_r_cvt"    , "B_i64_mr_mr_cvt"   , "B_i64_mr_t_cvt"    , 
    "B_i64_t_r_cvt"     , "B_i64_t_mr_cvt"    , "B_i64_t_t_cvt"     , "B_u64_r_r_cvt"     , "B_u64_r_mr_cvt"    , "B_u64_r_t_cvt"     , "B_u64_mr_r_cvt"    , "B_u64_mr_mr_cvt"   , "B_u64_mr_t_cvt"    , "B_u64_t_r_cvt"     , 
    "B_u64_t_mr_cvt"    , "B_u64_t_t_cvt"     , "B_f32_r_r_cvt"     , "B_f32_r_mr_cvt"    , "B_f32_r_t_cvt"     , "B_f32_mr_r_cvt"    , "B_f32_mr_mr_cvt"   , "B_f32_mr_t_cvt"    , "B_f32_t_r_cvt"     , "B_f32_t_mr_cvt"    , 
    "B_f32_t_t_cvt"     , "B_f64_r_r_cvt"     , "B_f64_r_mr_cvt"    , "B_f64_r_t_cvt"     , "B_f64_mr_r_cvt"    , "B_f64_mr_mr_cvt"   , "B_f64_mr_t_cvt"    , "B_f64_t_r_cvt"     , "B_f64_t_mr_cvt"    , "B_f64_t_t_cvt"     , 
    "B_B_r_r_cvt"       , "B_B_r_mr_cvt"      , "B_B_r_t_cvt"       , "B_B_mr_r_cvt"      , "B_B_mr_mr_cvt"     , "B_B_mr_t_cvt"      , "B_B_t_r_cvt"       , "B_B_t_mr_cvt"      , "B_B_t_t_cvt"       , 
    "f64_ls"            , "f64_le"            , "B_eq"              , "B_ne"              , "B_gt"              , "B_ge"              , "B_ls"              , "B_le"              , 
    "c_r_pop"           , "c_mr_pop"          , 
    "c_t_pop"           , "b_r_pop"           , "b_mr_pop"          , "b_t_pop"           , "i16_r_pop"         , "i16_mr_pop"        , "i16_t_pop"         , "u16_r_pop"         , "u16_mr_pop"        , "u16_t_pop"         , 
    "i32_r_pop"         , "i32_mr_pop"        , "i32_t_pop"         , "u32_r_pop"         , "u32_mr_pop"        , "u32_t_pop"         , "i64_r_pop"         , "i64_mr_pop"        , "i64_t_pop"         , "u64_r_pop"         , 
    "u64_mr_pop"        , "u64_t_pop"         , "f32_r_pop"         , "f32_mr_pop"        , "f32_t_pop"         , "f64_r_pop"         , "f64_mr_pop"        , "f64_t_pop"         , "o_r_pop"           , "o_mr_pop"          , 
    "o_t_pop"           , "B_r_pop"           , "B_mr_pop"          , "B_t_pop"           , 
    "c_push"            , "b_push"            , "i16_push"          , "u16_push"          , "i32_push"          , "u32_push"          , 
    "i64_push"          , "u64_push"          , "f32_push"          , "f64_push"          , 
    "c_pvar"            , "b_pvar"            , "i16_pvar"          , "u16_pvar"          , "i32_pvar"          , "u32_pvar"          , 
    "i64_pvar"          , "u64_pvar"          , "f32_pvar"          , "f64_pvar"          , "o_pvar"            , "B_pvar"            , 
    "c_pglo"            , "b_pglo"            , "i16_pglo"          , "u16_pglo"          , 
    "i32_pglo"          , "u32_pglo"          , "i64_pglo"          , "u64_pglo"          , "f32_pglo"          , "f64_pglo"          , "o_pglo"            , "B_pglo"            , 
    "c_cpy"             , "b_cpy"             , 
    "i16_cpy"           , "u16_cpy"           , "i32_cpy"           , "u32_cpy"           , "i64_cpy"           , "u64_cpy"           , "f32_cpy"           , "f64_cpy"           , "o_cpy"             , "B_cpy"             , 

    "setlocal"          , 
    "getarg"            , 
    "call"              , 
    "ecall"             ,
    "vcall"             , 
    "setarg"            , 
    "ret"               , 
    "vret"              , 

    "unknown"
};

const std::string pretreatCommandString[] {
    "RELY", "EXTERN", "EXPOSE", "LABEL", "GLOMEM", "HINT", "DEF", "unknown"
};

extern const int commandNumber = 1958, pretreatCommandNumber = 7;

Command getCommand(const std::string &_name) {
    for (int i = 0; i < commandNumber; i++) if (_name == commandString[i]) return (Command)i;
    return (Command)commandNumber;
}
PretreatCommand getPretreatCommand(const std::string &_name) {
    for (int i = 0; i < pretreatCommandNumber; i++) if (_name == pretreatCommandString[i]) return (PretreatCommand)i;
    return (PretreatCommand)pretreatCommandNumber;
}